// Generated by CoffeeScript 2.7.0
// Generated by CoffeeScript 2.7.0
var AppImages;

AppImages = {
  landing: {
    calendar: 'calendar.png',
    memories: 'memories.png',
    childInfo: 'child-info.png',
    emotionMeter: 'emotion-meter.gif',
    customDocHeaders: 'customDocHeaders.gif',
    tableOfContents: 'tableOfContents.png',
    expenseTracker: 'expense-tracker.png',
    collaboration: 'menu.png',
    phone: 'devices/phone.png',
    laptop: 'devices/laptop.png',
    tablet: 'devices/tablet.png'
  },
  brandLogos: {
    appleLogo: 'apple-logo.png',
    googleLogo: 'googlepay.png',
    payPal: 'paypal.png',
    venmo: 'venmo.png',
    zelle: 'zelle.png',
    cashapp: 'cashapp.png',
    applePay: 'applepay.png'
  },
  onboarding: {
    calendar: 'calendar.gif',
    welcome: 'welcome.gif'
  }
};

export default AppImages;

//# sourceMappingURL=appImages.js.map
