// Generated by CoffeeScript 2.7.0
// Generated by CoffeeScript 2.7.0
var AppImageNames;

AppImageNames = {
  dirs: {
    landing: 'landing',
    brandLogos: 'brandLogos',
    onboarding: 'onboarding'
  },
  misc: {
    brokenImagePlaceholder: 'broken-image-placeholder.png'
  },
  landing: {
    calendar: 'calendar.png',
    memories: 'memories.png',
    childInfo: 'child-info.png',
    emotionMeter: 'emotion-meter.gif',
    customDocHeaders: 'customDocHeaders.gif',
    tableOfContents: 'tableOfContents.png',
    expenseTracker: 'expense-tracker.png',
    collaboration: 'menu.png',
    phone: 'phone.png',
    laptop: 'laptop.png',
    tablet: 'tablet.png',
    logo: 'logo.png'
  },
  brandLogos: {
    appleLogo: 'apple-logo.png',
    googleLogo: 'googlepay.png',
    payPal: 'paypal.png',
    venmo: 'venmo.png',
    zelle: 'zelle.png',
    cashapp: 'cashapp.png',
    applePay: 'applepay.png'
  },
  onboarding: {
    calendar: 'calendar.gif',
    welcome: 'welcome.gif'
  }
};

export default AppImageNames;

//# sourceMappingURL=appImageNames.js.map
