// Generated by CoffeeScript 2.7.0
var AppImages

import Manager from "../managers/manager"
import ObjectManager from "../managers/objectManager"

AppImages = {
    // Directories
    dirs: {
        landing: "landing",
        brandLogos: "brandLogos",
        onboarding: "onboarding",
    },

    // Functions
    GetUrlFromName: function (name) {
        var imgObj, ref
        imgObj = ObjectManager.RecursivelyFlattenObjects(AppImages, "", {})
        if (Manager.IsValid(name, true)) {
            if (Manager.IsValid(imgObj) && Manager.IsValid(imgObj, true)) {
                return (ref = imgObj[name]) != null ? ref.url : void 0
            }
        }
        return null
    },

    // Firebase Storage Images
    // TESTING
    testing: {
        legalDoc: {
            name: "legalDoc",
            url: "https://firebasestorage.googleapis.com/v0/b/peaceful-coparenting.appspot.com/o/appImages%2Ftesting%2Flegal-doc.jpg?alt=media&token=8208f828-c8a5-42c3-809e-a43d3ed9fe3e",
        },
    },

    // CHANGELOG
    changelog: {
        cardBackground: {
            name: "cardBackground",
            url: "https://firebasestorage.googleapis.com/v0/b/peaceful-coparenting.appspot.com/o/appImages%2Fchangelog%2Fchangelog-card-background.jpg?alt=media&token=077e9ea0-6c18-475e-8d3d-603b4b300058",
        },
    },

    // MISC
    misc: {
        whiteInlineSpinner: {
            name: "whiteInlineSpinner",
            url: "https://firebasestorage.googleapis.com/v0/b/peaceful-coparenting.appspot.com/o/appImages%2Fmisc%2Fwhite-inline-loading-spinner.svg?alt=media&token=94eb7f59-1c5c-4387-b45d-b71aa43d2647",
        },
        inlineLoadingSpinner: {
            name: "inlineLoadingSpinner",
            url: "https://firebasestorage.googleapis.com/v0/b/peaceful-coparenting.appspot.com/o/appImages%2Fmisc%2Finline-loading-svg.svg?alt=media&token=99a1799f-e126-49a1-b573-dd0fadf24461",
        },
        starBackground: {
            name: "starBackground",
            url: "https://firebasestorage.googleapis.com/v0/b/peaceful-coparenting.appspot.com/o/appImages%2Fmisc%2FStarBackground.png?alt=media&token=87508d4e-ee11-4304-9afa-e6eb5751aa39",
        },
        launch: {
            name: "launch",
            url: "https://firebasestorage.googleapis.com/v0/b/peaceful-coparenting.appspot.com/o/appImages%2Fmisc%2Flaunch.gif?alt=media&token=f461b476-fbe4-400a-af71-bb1f1470db3f",
        },
        loadingGif: {
            name: "loading",
            url: "https://firebasestorage.googleapis.com/v0/b/peaceful-coparenting.appspot.com/o/appImages%2Fmisc%2Floading.gif?alt=media&token=33a4b3d3-f2d5-4e09-a2a9-a607f3a02505",
        },
        brokenImagePlaceholder: "broken-image-placeholder",
        safari: {
            name: "safari",
            url: "https://firebasestorage.googleapis.com/v0/b/peaceful-coparenting.appspot.com/o/appImages%2Fmisc%2Fsafari.png?alt=media&token=aa3e9550-3beb-4d44-862d-79d90ab45338",
        },
        desktopInstallation: {
            name: "desktopInstallation",
            url: "https://firebasestorage.googleapis.com/v0/b/peaceful-coparenting.appspot.com/o/appImages%2Fmisc%2FDesktopInstallation.png?alt=media&token=303f9520-5313-4f06-8485-ef8b17d80767",
        },
    },
    landing: {
        calendar: {
            name: "calendar",
            url: "https://firebasestorage.googleapis.com/v0/b/peaceful-coparenting.appspot.com/o/appImages%2Flanding%2Fcalendar.png?alt=media&token=718dc077-12f6-4c06-974a-7171b65a08d3",
        },
        memories: {
            name: "memories",
            url: "https://firebasestorage.googleapis.com/v0/b/peaceful-coparenting.appspot.com/o/appImages%2Flanding%2Fmemories.png?alt=media&token=eeb059fa-ec6c-49ae-a7c3-30948ec3ebd3",
        },
        childInfo: {
            name: "childInfo",
            url: "https://firebasestorage.googleapis.com/v0/b/peaceful-coparenting.appspot.com/o/appImages%2Flanding%2Fchild-info.png?alt=media&token=6aa24fc1-fa05-4b1d-aaa5-c47cc7b9b57a",
        },
        emotionMeter: {
            name: "emotionMeter",
            url: "https://firebasestorage.googleapis.com/v0/b/peaceful-coparenting.appspot.com/o/appImages%2Flanding%2Femotion-meter.gif?alt=media&token=c7c06a5e-cef6-4c15-aa02-e8d6a79828fa",
        },
        customDocHeaders: {
            name: "customDocHeaders",
            url: "https://firebasestorage.googleapis.com/v0/b/peaceful-coparenting.appspot.com/o/appImages%2Flanding%2FcustomDocHeaders.gif?alt=media&token=00f41b60-cf6d-41e1-8317-ed74628d3593",
        },
        tableOfContents: {
            name: "tableOfContents",
            url: "https://firebasestorage.googleapis.com/v0/b/peaceful-coparenting.appspot.com/o/appImages%2Flanding%2FtableOfContents.png?alt=media&token=76acc388-f0ce-42c2-8d76-18d0c0fc9482",
        },
        expenseTracker: {
            name: "expenseManagement",
            url: "https://firebasestorage.googleapis.com/v0/b/peaceful-coparenting.appspot.com/o/appImages%2Flanding%2Fexpense-tracker.png?alt=media&token=458198e5-cf0b-4bda-9cb7-f8149ee39bf6",
        },
        collaboration: {
            name: "menu",
            url: "https://firebasestorage.googleapis.com/v0/b/peaceful-coparenting.appspot.com/o/appImages%2Flanding%2Fmenu.png?alt=media&token=0e52ffa8-f6b0-47ca-8974-bb28562653ca",
        },
        phone: {
            name: "phone",
            url: "https://firebasestorage.googleapis.com/v0/b/peaceful-coparenting.appspot.com/o/appImages%2Flanding%2Fphone.png?alt=media&token=b481d6ce-bf8d-4e91-8f1a-98f24628f714",
        },
        laptop: {
            name: "laptop",
            url: "https://firebasestorage.googleapis.com/v0/b/peaceful-coparenting.appspot.com/o/appImages%2Flanding%2Flaptop.png?alt=media&token=a5cfabdb-322d-4356-a476-a62e85e1c08e",
        },
        tablet: {
            name: "tablet",
            url: "https://firebasestorage.googleapis.com/v0/b/peaceful-coparenting.appspot.com/o/appImages%2Flanding%2Ftablet.png?alt=media&token=cc5ed993-1cb9-4da8-b7ac-44d11057a165",
        },
        logo: {
            name: "logo",
            url: "https://firebasestorage.googleapis.com/v0/b/peaceful-coparenting.appspot.com/o/appImages%2Flogo.png?alt=media&token=0d7aa9e2-0765-40a0-9ff3-d7850b57d0fa",
        },
    },
    brandLogos: {
        appleLogo: "appleLogo",
        googleLogo: "googlepay",
        payPal: "paypal",
        venmo: "venmo",
        zelle: "zelle",
        cashapp: "cashapp",
        applePay: "applepay",
    },
    onboarding: {
        calendar: "calendar",
        welcome: "welcome",
    },
}

export default AppImages

//# sourceMappingURL=appImages.js.map