// Generated by CoffeeScript 2.7.0
// Generated by CoffeeScript 2.7.0
var ButtonTypes

ButtonTypes = {
  green: 'green',
  red: 'red',
  white: 'white',
  blend: 'blend',
}

export default ButtonTypes

//# sourceMappingURL=buttonThemes.js.map