# Generated by CoffeeScript 2.7.0

ButtonThemes =
  green: "green"
  red: "red"
  white: "white"
  blend: "blend"
  grey: "grey"
  accent: "accent"
  purple: "purple"
  lightPurple: "lightPurple"
  translucent:  "translucent"

export default ButtonThemes