# Generated by CoffeeScript 2.7.0

ButtonThemes =
  green: "green"
  red: "red"
  white: "white"
  blend: "blend"
  grey: "grey"
  accent: "accent"
  purple: "purple"
  brightPurple: "bright-purple"
  lightPurple: "lightPurple"
  translucent:  "translucent"
  yellow: "yellow"

export default ButtonThemes