// Generated by CoffeeScript 2.7.0
// Generated by CoffeeScript 2.7.0
var ButtonTypes;

ButtonTypes = {
  green: "green",
  red: "red",
  white: "white"
};

export default ButtonTypes;

//# sourceMappingURL=buttonTypes.js.map
