// Generated by CoffeeScript 2.7.0
// Generated by CoffeeScript 2.7.0
var ButtonThemes;

ButtonThemes = {
  green: "green",
  red: "red",
  white: "white",
  blend: "blend",
  grey: "grey",
  accent: "accent",
  purple: "purple",
  lightPurple: "lightPurple",
  translucent: "translucent"
};

export default ButtonThemes;

//# sourceMappingURL=buttonThemes.js.map
