// Generated by CoffeeScript 2.7.0
// Generated by CoffeeScript 2.7.0
var CreationForms;

CreationForms = {
  calendar: "calendar-event",
  expense: "expense-card",
  visitationChangeRequest: "visitation-change-request",
  handoffChangeRequest: "handoff-change-request",
  memories: "memory",
  documents: "documents",
  chat: "chat",
  coParent: "coParent"
};

export default CreationForms;

//# sourceMappingURL=creationForms.js.map
