// Generated by CoffeeScript 2.7.0
// Generated by CoffeeScript 2.7.0
var CreationForms;

CreationForms = {
  calendar: "new-calendar-event",
  expense: "new-expense-card",
  swapRequest: "swapRequest",
  transferRequest: "new-transfer-request",
  memories: "new-memory",
  documents: "documents",
  chat: "new-chat",
  coparent: "new-coparent"
};

export default CreationForms;

//# sourceMappingURL=creationForms.js.map
