// Generated by CoffeeScript 2.7.0
var DateTimePickerViews;

DateTimePickerViews = {
  datetime: ['day', 'month', 'year', 'hours', 'minutes'],
  monthAndDay: ['day', 'month'],
  timeOnly: ['hours', 'minutes'],
  monthAndYear: ['month', 'year'],
  monthDayYear: ['day', 'month', 'year']
};

export default DateTimePickerViews;

//# sourceMappingURL=datetimePickerViews.js.map
