// Generated by CoffeeScript 2.7.0
var DateFormats;

DateFormats = {
  withReadbleDay: 'dddd, MMMM DD, YYYY',
  readableDatetime: 'ddd, MMM DD @ hh:mma',
  fullDatetime: 'MM/DD/YYYY h:mma',
  readableMonthAndDay: 'dddd, MMMM DD',
  monthAndDay: 'MM/DD',
  dateForDb: 'MM/DD/YYYY',
  jsDateTime: 'yyyy,MM,DD h:mm a',
  timeForDb: 'h:mma',
  monthDayYear: 'MM/DD/YYYY',
  readableDay: 'dddd Do',
  monthOnly: "MM",
  readableMonth: "MMMM",
  summaryHour: "ha"
};

export default DateFormats;
