// Generated by CoffeeScript 2.7.0
var DatetimeFormats;

DatetimeFormats = {
  withReadableDay: 'dddd, MMMM DD, YYYY',
  readableDatetime: 'ddd, MMM DD (h:mma)',
  timestamp: 'MM/DD/YYYY h:mma',
  readableMonthAndDay: 'dddd, MMMM Do',
  readableMonthAndDayWithFullMonth: 'MMMM Do, YYYY',
  readableMonthAndDayShort: "MMM Do",
  readableMonthDayYear: 'MMMM DD, YYYY',
  readableMonthAndDayWithDayDigitOnly: 'MMMM Do',
  readableMonthAndDayWithYear: 'MMMM Do, YYYY',
  monthAndDay: 'MM/DD',
  dateForDb: 'MM/DD/YYYY',
  jsDateTime: 'yyyy,MM,DD h:mm a',
  jsDate: 'YYYY-MM-DD',
  timeForDb: 'h:mma',
  displayEndTime: '@ h:mma',
  monthDayYear: 'MM/DD/YYYY',
  readableDay: 'dddd Do',
  monthOnly: "MM",
  readableMonth: "MMMM",
  summaryHour: "ha"
};

export default DatetimeFormats;

//# sourceMappingURL=datetimeFormats.js.map
