// Generated by CoffeeScript 2.7.0
var ExpenseCategories

ExpenseCategories = [
  'Childcare',
  'Extracurricular Activities',
  'Sports',
  'Educational',
  'Medical',
  'Travel',
  'Transportation',
  'Dental',
  'Gifting',
  'Pet',
]

export default ExpenseCategories

//# sourceMappingURL=expenseCategories.js.map
