// Generated by CoffeeScript 2.7.0
var ExpenseCategories;

ExpenseCategories = {
  Childcare: 'Childcare',
  Clothing: 'Clothing',
  Educational: 'Educational',
  Entertainment: 'Entertainment',
  Dental: 'Dental',
  Gifting: 'Gifting',
  Medical: 'Medical',
  Miscellaneous: 'Miscellaneous',
  Pet: 'Pet',
  Sports: 'Sports',
  Transportation: 'Transportation',
  Travel: 'Travel'
};

export default ExpenseCategories;

//# sourceMappingURL=expenseCategories.js.map
