// Generated by CoffeeScript 2.7.0
var ExpenseSortByTypes;

ExpenseSortByTypes = {
  nearestDueDate: 'Nearest Due Date',
  recentlyAdded: 'Recently Added',
  amountDesc: 'Amount: High to Low',
  amountAsc: 'Amount: Low to High',
  nameAsc: 'Name (ascending)',
  nameDesc: 'Name (descending)'
};

export default ExpenseSortByTypes;

//# sourceMappingURL=expenseSortByTypes.js.map
