// Generated by CoffeeScript 2.7.0
var FeedbackEmotion;

FeedbackEmotion = {
  neutral: "neutral",
  love: "love",
  unhappy: "unhappy",
  peaceful: "peaceful"
};

export default FeedbackEmotion;

//# sourceMappingURL=feedbackEmotions.js.map
