// Generated by CoffeeScript 2.7.0
var FormNames

FormNames = {
    calendar: 'calendar',
    visitationChangeRequest: 'visitationChangeRequest',
    handoffChangeRequest: 'handoffChangeRequest',
    expense: 'expense',
    memories: 'memories',
}

export default FormNames

//# sourceMappingURL=formNames.js.map