// Generated by CoffeeScript 2.7.0
// Generated by CoffeeScript 2.7.0
var InputTypes;

InputTypes = {
  text: 'text',
  number: 'number',
  email: 'email',
  password: 'password',
  date: 'date',
  dateRange: 'date-range',
  time: 'time',
  textarea: 'textarea',
  phone: 'phone',
  url: 'url'
};

export default InputTypes;

//# sourceMappingURL=inputTypes.js.map
