# Generated by CoffeeScript 2.7.0

InputTypes = {
  text: 'text',
  number: 'number',
  email: 'email',
  password: 'password',
  date: 'date',
  dateRange: 'date-range'
  time: 'time'
  address: 'address'
  textarea: 'textarea'
  phone: 'phone'
  url: 'url'
}

export default InputTypes