// Generated by CoffeeScript 2.7.0
var MultilineDetailBlockTypes;

MultilineDetailBlockTypes = {
  Reminders: 'Reminders',
  Children: 'Children',
  ShareWith: 'ShareWith'
};

export default MultilineDetailBlockTypes;

//# sourceMappingURL=multilineDetailBlockTypes.js.map
