// Generated by CoffeeScript 2.7.0
var ReminderTimes;

ReminderTimes = {
  fiveMinutes: 'fiveMinutes',
  hour: 'hour',
  halfHour: 'halfHour',
  timeOfEvent: 'timeOfEvent'
};

export default ReminderTimes;

//# sourceMappingURL=reminderTimes.js.map
