// Generated by CoffeeScript 2.7.0
var ScheduleTypes

ScheduleTypes = {
  variableWeekends: 'variableWeekends',
  fiftyFifty: 'fiftyFifty',
  everyOtherWeekend: 'everyOtherWeekend',
  specificWeekends: 'specificWeekends',
  everyWeekend: 'everyWeekend',
}

export default ScheduleTypes
