// Generated by CoffeeScript 2.7.0
var ScheduleTypes

ScheduleTypes = {
  variableWeekends: 'variableWeekends',
  fiftyFifty: 'fiftyFifty',
  everyOtherWeekend: 'everyOtherWeekend',
  customWeekends: 'customWeekends',
  everyWeekend: 'everyWeekend',
}

export default ScheduleTypes

//# sourceMappingURL=scheduleTypes.js.map
