// Generated by CoffeeScript 2.7.0
var ScreensToHideCenterNavbarButton;

import ScreenNames from "./screenNames";

ScreensToHideCenterNavbarButton = [ScreenNames.account, ScreenNames.settings, ScreenNames.contactUs, ScreenNames.visitation];

export default ScreensToHideCenterNavbarButton;

//# sourceMappingURL=screensToHideCenterNavbarButton.js.map
