// Generated by CoffeeScript 2.7.0
var ScreensToHideCenterNavbarButton

import ScreenNames from './screenNames'

ScreensToHideCenterNavbarButton = [
  ScreenNames.account,
  ScreenNames.settings,
  ScreenNames.contactUs,
  ScreenNames.visitation,
  ScreenNames.adminDashboard,
  ScreenNames.chat,
  ScreenNames.activity,
]

export default ScreensToHideCenterNavbarButton

//# sourceMappingURL=screensToHideCenterNavbarButton.js.map