// Generated by CoffeeScript 2.7.0
var StateObj;

import ScreenNames from "./screenNames";

import ActivitySet from "../models/activitySet";

StateObj = {
  activeInfoChild: null,
  activitySet: new ActivitySet(),
  currentScreen: ScreenNames.login,
  currentUser: {},
  activeInfoCoparent: [],
  docToView: '',
  firebaseUser: null,
  isLoading: true,
  menuIsOpen: false,
  messageToUser: null,
  modalIsOpen: false,
  navbarButton: {},
  selectedChild: null,
  selectedNewEventDay: null,
  swapRequestToRevise: null,
  showNavbar: true,
  showCenterNavbarButton: true,
  theme: 'light',
  transferRequestToEdit: {},
  unreadMessageCount: 0,
  userIsLoggedIn: false,
  users: [],
  updateAvailable: false,
  viewExpenseForm: false,
  viewSwapRequestForm: false,
  viewTransferRequestForm: false,
  setActivitySet: function(set) {},
  setActiveInfoChild: function(child) {},
  setActiveInfoCoparent: function(coparent) {},
  setContactInfoToUpdateType: function() {},
  setCurrentScreen: function(screen) {},
  setCurrentUser: function(user) {},
  setDateToEdit: function(date) {},
  setDocToView: function(doc) {},
  setEventToEdit: function(event) {},
  setFirebaseUser: function(user) {},
  setIsLoading: function(bool) {},
  setMenuIsOpen: function(isOpen) {},
  setMessageToUser: function(user) {},
  setModalIsOpen: function(bool) {},
  setNavbarButton: function(button) {},
  setSelectedChild: function(child) {},
  setSelectedNewEventDay: function(day) {},
  setSwapRequestToRevise: function(request) {},
  setShowCenterNavbarButton: function(bool) {},
  setShowOverlay: function(bool) {},
  setTheme: function(theme) {},
  setTransferRequestToEdit: function(request) {},
  setUpdateAvailable: function(bool) {},
  setUnreadMessageCount: function(num) {},
  setUserIsLoggedIn: function(isLoggedIn) {},
  setUsers: function(users) {},
  setViewExpenseForm: function(show) {},
  setViewSwapRequestForm: function(show) {},
  setViewTransferRequestForm: function(show) {}
};

export default StateObj;

//# sourceMappingURL=stateObj.js.map
