// Generated by CoffeeScript 2.7.0
var StateObj;

import ScreenNames from "./screenNames";

import DateFormats from "./datetimeFormats";

import moment from "moment";

StateObj = {
  authUser: null,
  childAccessGranted: false,
  creationFormToShow: '',
  currentScreen: ScreenNames.home,
  currentUser: {},
  docToView: '',
  isLoading: true,
  loadingText: 'Preparing your pathway to peace...',
  menuIsOpen: false,
  messageToUser: null,
  dateToEdit: moment().format(DateFormats.dateForDb),
  modalIsOpen: false,
  notificationCount: 0,
  parentAccessGranted: false,
  refreshKey: 0,
  showCreationMenu: false,
  showScreenActions: false,
  registrationUserName: '',
  successAlertMessage: null,
  setSuccessAlertMessage: function(message) {},
  setShowScreenActions: function(bool) {},
  setAuthUser: function(user) {},
  setChildAccessGranted: function(bool) {},
  setContactInfoToUpdateType: function() {},
  setCreationFormToShow: function(form) {},
  setCurrentScreen: function(screen) {},
  setCurrentUser: function(user) {},
  setDateToEdit: function(date) {},
  setDocToView: function(doc) {},
  setEventToEdit: function(event) {},
  setIsLoading: function(bool) {},
  setLoadingText: function(text) {},
  setMenuIsOpen: function(isOpen) {},
  setMessageToUser: function(user) {},
  setModalIsOpen: function(bool) {},
  setNotificationCount: function(count) {},
  setParentAccessGranted: function(bool) {},
  setRefreshKey: function(num) {},
  setRegistrationUserName: function(name) {},
  setShowBottomMenu: function(bool) {},
  setShowOverlay: function(bool) {},
  setTheme: function(theme) {},
  setUserIsLoggedIn: function(isLoggedIn) {},
  showBottomMenu: false,
  theme: 'light',
  userIsLoggedIn: false
};

export default StateObj;

//# sourceMappingURL=stateObj.js.map
