// Generated by CoffeeScript 2.7.0
var StateObj

import moment from "moment"

import DateFormats from "./datetimeFormats"
import ScreenNames from "./screenNames"

StateObj = {
    // Getters
    activeChatId: "",
    authUser: null,
    childAccessGranted: false,
    creationFormToShow: "",
    currentScreen: ScreenNames.landing,
    currentUser: {},
    docToView: "",
    docViewerUrl: "",
    isLoading: true,
    menuIsOpen: false,
    messageToUser: null,
    modalIsOpen: false,
    notificationCount: 0,
    oneSignalInitialized: false,
    parentAccessGranted: false,
    refreshKey: 0,
    registrationExitStep: "",
    registrationUserName: "",
    selectedCalendarDate: moment().format(DateFormats.dateForDb),
    showCreationMenu: false,
    showOverlay: false,
    showScreenActions: false,
    bannerMessage: null,
    bannerType: "success",
    users: [],

    // Setters
    setActiveChatId: function (id) {},
    setAuthUser: function (user) {},
    setBannerType: function (type) {},
    setChildAccessGranted: function (bool) {},
    setContactInfoToUpdateType: function () {},
    setCreationFormToShow: function (form) {},
    setCurrentScreen: function (screen) {},
    setCurrentUser: function (user) {},
    setDocToView: function (doc) {},
    setDocViewerUrl: function (url) {},
    setEventToEdit: function (event) {},
    setIsLoading: function (bool) {},
    setMenuIsOpen: function (isOpen) {},
    setMessageToUser: function (user) {},
    setModalIsOpen: function (bool) {},
    setNotificationCount: function (count) {},
    setParentAccessGranted: function (bool) {},
    setRefreshKey: function (num) {},
    setRegistrationExitStep: function (step) {},
    setRegistrationUserName: function (name) {},
    setSelectedCalendarDate: function (date) {},
    setShowBottomMenu: function (bool) {},
    setShowOverlay: function (bool) {},
    setShowScreenActions: function (bool) {},
    setBannerMessage: function (message) {},
    setTheme: function (theme) {},
    setUserIsLoggedIn: function (isLoggedIn) {},
    setUsers: function (users) {},
    showBottomMenu: false,
    theme: "light",
    userIsLoggedIn: false,
}

export default StateObj

//# sourceMappingURL=stateObj.js.map