// Generated by CoffeeScript 2.7.0
var UpdateCategory

UpdateCategory = {
    id: '',
    calendar: 'calendar',
    childInfo: {
        medical: 'medical',
        behavior: 'behavior',
        general: 'general',
        schooling: 'schooling',
    },
    chats: 'chats',
    expenses: 'expenses',
    visitationChangeRequest: 'visitation request',
    handoffChangeRequest: 'handoff request',
    documents: 'documents',
    memories: 'memories',
}

export default UpdateCategory

//# sourceMappingURL=updateCategory.js.map