// Generated by CoffeeScript 2.7.0
var UpdateCategory;

UpdateCategory = {
  id: '',
  calendar: 'calendar',
  childInfo: {
    medical: 'medical',
    behavior: 'behavior',
    general: 'general',
    schooling: 'schooling'
  },
  chats: "chats",
  expenses: "expenses",
  swapRequest: "swap request",
  transferRequest: "transfer request",
  documents: "documents",
  memories: "memories"
};

export default UpdateCategory;

//# sourceMappingURL=updateCategory.js.map
