// Generated by CoffeeScript 2.7.0
var Views;

Views = {
  DetailsEdit: {
    Default: [
      {
        label: 'Details',
        value: 'details'
      }
    ],
    Details: [
      {
        label: 'Details',
        value: 'details'
      }
    ],
    Edit: [
      {
        label: 'Edit',
        value: 'edit'
      }
    ],
    All: [
      {
        label: 'Details',
        value: 'details'
      },
      {
        label: 'Edit',
        value: 'edit'
      }
    ]
  }
};

export default Views;

//# sourceMappingURL=views.js.map
