// Generated by CoffeeScript 2.7.0
var AccountsMapper

import Manager from '../managers/manager'

import StringManager from '../managers/stringManager'

AccountsMapper = {
    GetShareWithNames: function (currentUser, users, shareWith) {
        var filtered, mappedShareWithNames
        filtered =
            shareWith != null
                ? shareWith.filter(function (x) {
                      return (
                          x !== (currentUser != null ? currentUser.key : void 0) &&
                          (currentUser != null ? currentUser.sharedDataUsers.includes(x) : void 0)
                      )
                  })
                : void 0
        if (!Manager.IsValid(filtered)) {
            return false
        }
        mappedShareWithNames = Manager.MapKeysToUsers(filtered, users)
        mappedShareWithNames = mappedShareWithNames.filter(function (x) {
            return (x != null ? x.name : void 0) !== StringManager.GetFirstNameOnly(currentUser != null ? currentUser.name : void 0)
        })
        return mappedShareWithNames
    },
}

export default AccountsMapper

//# sourceMappingURL=accountsMapper.js.map