// Generated by CoffeeScript 2.7.0
var UserMapper;

import DB from "../database/DB";

import Manager from "../managers/manager";

UserMapper = {
  childrenToChildAccounts: async function(children) {
    var child, childAccounts, i, len, thisChild, users;
    childAccounts = [];
    users = (await DB.getTable(DB.tables.users));
    for (i = 0, len = children.length; i < len; i++) {
      child = children[i];
      thisChild = (await DB.find(users, ["phone", child != null ? child.phone : void 0], true));
      if (Manager.isValid(thisChild)) {
        childAccounts.push(thisChild);
      }
    }
    return childAccounts;
  }
};

export default UserMapper;

//# sourceMappingURL=userMapper.js.map
