// Generated by CoffeeScript 2.7.0
var UserMapper;

import DB from "../database/DB";

import Manager from "../managers/manager";

UserMapper = {
  childrenToChildAccounts: async function(children) {
    var child, childAccounts, i, len, ref, thisChild;
    childAccounts = [];
    if (Manager.isValid(children, true)) {
      for (i = 0, len = children.length; i < len; i++) {
        child = children[i];
        thisChild = (await DB.find(DB.tables.users, ["phone", child != null ? (ref = child.general) != null ? ref.phone : void 0 : void 0], true));
        if (Manager.isValid(thisChild)) {
          childAccounts.push(thisChild);
        }
      }
    }
    return childAccounts;
  }
};

export default UserMapper;

//# sourceMappingURL=userMapper.js.map
