// Generated by CoffeeScript 2.7.0
var UserMapper;

import DB from "../database/DB";

import Manager from "../managers/manager";

import DB_UserScoped from "../database/DB_UserScoped";

UserMapper = {
  childrenToChildAccounts: async function(authUserEmail) {
    var child, childAccounts, currentUser, i, len, ref, thisChild;
    currentUser = (await DB_UserScoped.getCurrentUser(authUserEmail));
    childAccounts = [];
    if (Manager.isValid(children)) {
      for (i = 0, len = children.length; i < len; i++) {
        child = children[i];
        thisChild = (await DB.find(DB.tables.users, ["phone", child != null ? (ref = child.general) != null ? ref.phone : void 0 : void 0], true));
        if (Manager.isValid(thisChild)) {
          childAccounts.push(thisChild);
        }
      }
    }
    return childAccounts;
  },
  childAccountToUserRecord: async function(authUserEmail, childAccountKey) {
    var currentUser;
    return currentUser = (await DB_UserScoped.getCurrentUser(authUserEmail));
  }
};

export default UserMapper;

//# sourceMappingURL=userMapper.js.map
