// Generated by CoffeeScript 2.7.0
var VisitationMapper

import ReminderTimes from 'constants/reminderTimes'

import DateManager from 'managers/dateManager'

import ScheduleTypes from 'constants/scheduleTypes'

VisitationMapper = {
  formattedScheduleTypes: function (type) {
    switch (true) {
      case type.contains('50'):
        return ScheduleTypes.fiftyFifty
      case type.contains('Custom Weekends'):
        return ScheduleTypes.customWeekends
      case type.contains('Every Weekend'):
        return ScheduleTypes.everyWeekend
      case type.contains('Every other Weekend'):
        return ScheduleTypes.everyOtherWeekend
    }
    return null
  },
}

export default VisitationMapper

//# sourceMappingURL=visitationMapper.js.map
