// Generated by CoffeeScript 2.7.0
var VisitationMapper;

import ReminderTimes from 'constants/reminderTimes';

import DateManager from 'managers/dateManager';

import scheduleTypes from 'constants/scheduleTypes';

VisitationMapper = {
  formattedScheduleTypes: function(type) {
    switch (true) {
      case type.contains('50'):
        return scheduleTypes.fiftyFifty;
      case type.contains('Specific Weekends'):
        return scheduleTypes.variableWeekends;
      case type.contains('Every Weekend'):
        return scheduleTypes.weekends;
      case type.contains('Every other Weekend'):
        return scheduleTypes.weekends;
    }
    return null;
  }
};

export default VisitationMapper;

//# sourceMappingURL=visitationMapper.js.map
