// Generated by CoffeeScript 2.7.0
var VisitationMapper;

import ScheduleTypes from '../constants/scheduleTypes';

import Manager from "../managers/manager";

VisitationMapper = {
  formattedScheduleTypes: function(type) {
    console.log(type);
    switch (true) {
      case Manager.contains(type, '50'):
        return ScheduleTypes.fiftyFifty;
      case Manager.contains(type, 'Custom Weekends'):
        return ScheduleTypes.customWeekends;
      case Manager.contains(type, 'Every Weekend'):
        return ScheduleTypes.everyWeekend;
      case Manager.contains(type, 'Every other Weekend'):
        return ScheduleTypes.everyOtherWeekend;
    }
    return null;
  }
};

export default VisitationMapper;

//# sourceMappingURL=visitationMapper.js.map
