// Generated by CoffeeScript 2.7.0
var Behavior

export default Behavior = class Behavior {
  constructor(counselorName = '', issues = '', phone = '') {
    this.counselorName = counselorName
    this.issues = issues
    this.phone = phone
  }
}
