// Generated by CoffeeScript 2.7.0
var ChildUser;

import Manager from '../../managers/manager.js';

export default ChildUser = class ChildUser {
  constructor(parents = [], name = '', email = '', accountType = 'child', phone = '', notificationsEnabled = true, id = Manager.getUid(), settings = {
      theme: 'light'
    }, dailySummaries = {
      morningSentDate: '',
      eveningSentDate: '',
      morningReminderSummaryHour: '10am',
      eveningReminderSummaryHour: '8pm'
    }, parentAccessGranted = false) {
    this.parents = parents;
    this.name = name;
    this.email = email;
    this.accountType = accountType;
    this.phone = phone;
    this.notificationsEnabled = notificationsEnabled;
    this.id = id;
    this.settings = settings;
    this.dailySummaries = dailySummaries;
    this.parentAccessGranted = parentAccessGranted;
  }

};

//# sourceMappingURL=childUser.js.map
