// Generated by CoffeeScript 2.7.0
var ChildUser;

import Manager from '@manager';

export default ChildUser = class ChildUser {
  constructor(_name = 'name', _id = '', _allowNotifications = 'Yes', _email = 'email', _phone = 'phone', _accountType = 'child', _parents = [], _settings = {
      morningReminderSummaryHour: '10am',
      eveningReminderSummaryHour: '8pm'
    }) {
    this.parents = _parents;
    this.name = _name;
    this.email = _email;
    this.phone = _phone;
    this.accountType = _accountType;
    this.allowNotifications = _allowNotifications;
    this.id = Manager.getUid();
    this.settings = _settings;
  }

};

//# sourceMappingURL=childUser.js.map
