// Generated by CoffeeScript 2.7.0
var Child;

import Manager from '../../managers/manager';

import General from './general';

import Medical from './medical';

import Schooling from './schooling';

import Behavior from './behavior';

export default Child = class Child {
  constructor(id = Manager.getUid(), general = new General(), medical = new Medical(), schooling = new Schooling(), behavior = new Behavior(), sharing = []) {
    this.id = id;
    this.general = general;
    this.medical = medical;
    this.schooling = schooling;
    this.behavior = behavior;
    this.sharing = sharing;
  }

};

//# sourceMappingURL=child.js.map
