// Generated by CoffeeScript 2.7.0
var Child

import Manager from '../../managers/manager'

import Behavior from './behavior'

import General from './general'

import Medical from './medical'

import Schooling from './schooling'

Child = class Child {
    constructor(
        id = Manager.GetUid(),
        general = new General(),
        medical = new Medical(),
        schooling = new Schooling(),
        behavior = new Behavior(),
        checklists = [],
        userKey = ''
    ) {
        this.id = id
        this.general = general
        this.medical = medical
        this.schooling = schooling
        this.behavior = behavior
        this.checklists = checklists
        this.userKey = userKey
    }
}

export default Child

//# sourceMappingURL=child.js.map