// Generated by CoffeeScript 2.7.0
var General;

import Manager from '@manager';

export default General = class General {
  constructor(dateOfBirth = '', address = '', phone = '', name = '', gender = '', profilePic = '') {
    this.dateOfBirth = dateOfBirth;
    this.address = address;
    this.phone = phone;
    this.name = name;
    this.gender = gender;
    this.profilePic = profilePic;
  }

};

//# sourceMappingURL=general.js.map
