// Generated by CoffeeScript 2.7.0
var General;

General = class General {
  constructor(dateOfBirth = '', address = '', phone = '', name = '', profilePic = '', email = '') {
    this.dateOfBirth = dateOfBirth;
    this.address = address;
    this.phone = phone;
    this.name = name;
    this.profilePic = profilePic;
    this.email = email;
  }

};

export default General;

//# sourceMappingURL=general.js.map
