// Generated by CoffeeScript 2.7.0
var Medical;

export default Medical = class Medical {
  constructor(doctorName = '', doctorPhone = '', allergy = [], shareWith = []) {
    this.doctorName = doctorName;
    this.doctorPhone = doctorPhone;
    this.allergy = allergy;
    this.shareWith = shareWith;
  }

};
