// Generated by CoffeeScript 2.7.0
var Medical;

export default Medical = class Medical {
  constructor(doctorName = '', shareWith = []) {
    this.doctorName = doctorName;
    this.shareWith = shareWith;
  }

};

//# sourceMappingURL=medical.js.map
