// Generated by CoffeeScript 2.7.0
var Medical;

Medical = class Medical {
  constructor(doctorName = '', shareWith = []) {
    this.doctorName = doctorName;
    this.shareWith = shareWith;
  }

};

export default Medical;

//# sourceMappingURL=medical.js.map
