// Generated by CoffeeScript 2.7.0
var Schooling;

Schooling = class Schooling {
  constructor(schoolName = '', grade = '') {
    this.schoolName = schoolName;
    this.grade = grade;
  }

};

export default Schooling = class Schooling {};

//# sourceMappingURL=schooling.js.map
