// Generated by CoffeeScript 2.7.0
var Schooling

export default Schooling = class Schooling {
  constructor(schoolName = '', grade = '') {
    this.schoolName = schoolName
    this.grade = grade
  }
}
