// Generated by CoffeeScript 2.7.0
var AppManager;

import Manager from "./manager";

import DB from "../database/DB";

import DateManager from "./dateManager";

import moment from "moment";

import {
  child,
  getDatabase,
  ref,
  set
} from 'firebase/database';

import DateFormats from "../constants/dateFormats";

import DB_UserScoped from "../database/db_userScoped";

export default AppManager = {
  setAppBadge: (count) => {
    if (window.navigator.setAppBadge) {
      return window.navigator.setAppBadge(count);
    }
  },
  clearAppBadge: () => {},
  //    window.navigator.clearAppBadge()
  isDevMode: () => {
    return location.hostname === 'localhost';
  },
  getAccountType: (currentUser) => {
    if (Manager.isValid(currentUser)) {
      if (Manager.isValid(currentUser.accountType)) {
        if (currentUser.accountType === 'parent') {
          return 'parent';
        } else {
          return 'child';
        }
      }
      return 'parent';
    }
  },
  hidePopupCard: () => {
    var cardContainer;
    cardContainer = document.getElementById("popup-card-container");
    if (cardContainer) {
      return cardContainer.classList.remove("active");
    }
  },
  applyVersionNumberToUrl: () => {
    var formattedUpdateUrl, formattedUpdateUrlWithOneVersion, versionNumber;
    versionNumber = Manager.getUid().substring(0, 4);
    formattedUpdateUrl = window.location.href.replaceAll(versionNumber, '');
    formattedUpdateUrlWithOneVersion = formattedUpdateUrl.substring(0, formattedUpdateUrl.indexOf("/") + versionNumber);
    return history.replaceState(versionNumber, '', formattedUpdateUrlWithOneVersion);
  },
  setHolidays: async(currentUser) => {
    var cal, holidays;
    cal = (await DB.getTable(DB.tables.calendarEvents));
    holidays = cal.filter((x) => {
      return x.isHoliday === true;
    });
    if (holidays.length === 0) {
      return (await DateManager.setHolidays(currentUser));
    }
  },
  deleteExpiredCalendarEvents: async function() {
    var daysPassed, event, events, i, len;
    events = (await DB.getTable(DB.tables.calendarEvents));
    if (!Array.isArray(events)) {
      events = Manager.convertToArray(events);
    }
    if (Manager.isValid(events, true)) {
      events = events.filter(function(x) {
        return x != null;
      });
      for (i = 0, len = events.length; i < len; i++) {
        event = events[i];
        if (!(Manager.isValid(event))) {
          continue;
        }
        daysPassed = DateManager.getDuration('days', moment(), event.fromDate);
        if (daysPassed <= -30 && !event.isHoliday) {
          await DB.delete(DB.tables.calendarEvents, event.id);
          return;
        }
      }
    }
  },
  setUpdateAvailable: async function(updateAvailableValue = null) {
    var dbRef, i, lastUpdateObject, len, timestamp, updateAvailable, updateObject, user, users;
    dbRef = ref(getDatabase());
    users = Manager.convertToArray((await DB.getTable(DB.tables.users)));
// Set updatedAp to false for all users to show update alert
    for (i = 0, len = users.length; i < len; i++) {
      user = users[i];
      await DB_UserScoped.updateUserRecord(user.phone, "updatedApp", false);
    }
    lastUpdateObject = (await DB.getTable("updateAvailable"));
    ({updateAvailable} = lastUpdateObject);
    timestamp = moment().format(DateFormats.fullDatetime);
    updateObject = {
      lastUpdate: timestamp,
      updateAvailable: false
    };
    if (updateAvailableValue !== null && updateAvailableValue !== void 0) {
      updateObject.lastUpdate = timestamp;
      updateAvailable = false;
      set(child(dbRef, "updateAvailable"), updateObject);
      return false;
    }
    if (!Manager.isValid(updateAvailable) || updateAvailable === false) {
      updateObject.updateAvailable = true;
      return set(child(dbRef, "updateAvailable"), updateObject);
    }
  },
  getLastUpdateObject: async function() {
    var updateObject;
    updateObject = (await DB.getTable("updateAvailable"));
    return updateObject;
  },
  deleteExpiredMemories: async function() {
    var i, key, len, memories, memory, results;
    memories = (await DB.getTable(DB.tables.memories));
    if (Manager.isValid(memories, true)) {
      results = [];
      for (i = 0, len = memories.length; i < len; i++) {
        memory = memories[i];
        if (DateManager.getDuration("days", moment(memory != null ? memory.creationDate : void 0), moment()) > 28) {
          key = (await DB.getNestedSnapshotKey("memories", memory, "id"));
          results.push((await DB.deleteByPath(`memories/${key}`)));
        } else {
          results.push(void 0);
        }
      }
      return results;
    }
  }
};

//# sourceMappingURL=appManager.js.map
