// Generated by CoffeeScript 2.7.0
var CalendarManager;

import DB from "@db";

import "../prototypes";

import calMapper from "../mappers/calMapper";

import {
  child,
  get,
  getDatabase,
  push,
  ref,
  remove,
  set,
  update
} from 'firebase/database';

import Manager from "./manager";

import {
  toCamelCase,
  getFirstWord,
  formatFileName,
  isAllUppercase,
  removeSpacesAndLowerCase,
  stringHasNumbers,
  wordCount,
  uppercaseFirstLetterOfAllWords,
  spaceBetweenWords,
  formatNameFirstNameOnly,
  removeFileExtension
} from "../globalFunctions";

export default CalendarManager = {
  getUniqueArrayOfObjects: (arr, key) => {
    var i, len, obj, output, results;
    output = Object.entries(Object.assign({}, ...arr));
    results = [];
    for (i = 0, len = output.length; i < len; i++) {
      obj = output[i];
      results.push(obj[1]);
    }
    return results;
  },
  formatEventTitle: (title) => {
    if (title && title.length > 0) {
      title = uppercaseFirstLetterOfAllWords(title);
      title = title.replaceAll("To", "to").replaceAll("Vs", "vs").replaceAll("With", "with").replaceAll("At", "at").replaceAll("From", "from").replaceAll("The", "the").replaceAll("And", "and");
      return title;
    }
  },
  hideCalendar: () => {
    var allCals;
    allCals = document.querySelectorAll(".flatpickr-calendar");
    if (allCals && allCals.length > 0) {
      return allCals.forEach((cal) => {
        return cal.remove();
      });
    }
  },
  addMultipleCalEvents: async function(newEvents) {
    var currentEvents, dbRef, error, eventsToAdd;
    dbRef = ref(getDatabase());
    currentEvents = Manager.convertToArray((await DB.getTable(DB.tables.calendarEvents)));
    eventsToAdd = [...currentEvents, ...newEvents].filter(function(x) {
      return x != null;
    }).flat();
    try {
      return (await set(child(dbRef, `${DB.tables.calendarEvents}`), eventsToAdd));
    } catch (error1) {
      error = error1;
    }
  },
  addCalendarEvent: async function(data) {
    var currentEvents, dbRef;
    dbRef = ref(getDatabase());
    currentEvents = Manager.convertToArray((await DB.getTable(DB.tables.calendarEvents)));
    currentEvents = currentEvents.filter(function(n) {
      return n;
    });
    return set(child(dbRef, `${DB.tables.calendarEvents}`), [...currentEvents, data]);
  },
  deleteMultipleEvents: async function(events, currentUser) {
    var dbRef, holiday, i, idToDelete, len, results, tableRecords, userHolidays;
    dbRef = ref(getDatabase());
    tableRecords = Manager.convertToArray((await DB.getTable(DB.tables.calendarEvents)));
    userHolidays = tableRecords.filter((x) => {
      return x.phone === currentUser.phone && x.isHoliday === true;
    });
    results = [];
    for (i = 0, len = userHolidays.length; i < len; i++) {
      holiday = userHolidays[i];
      idToDelete = (await DB.getSnapshotKey(DB.tables.calendarEvents, holiday, 'id'));
      results.push((await remove(child(dbRef, `${DB.tables.calendarEvents}/${idToDelete}/`))));
    }
    return results;
  },
  deleteEvent: async function(tableName, id) {
    var dbRef, i, idToDelete, len, record, results, tableRecords;
    dbRef = ref(getDatabase());
    idToDelete = null;
    tableRecords = Manager.convertToArray((await DB.getTable(tableName)));
    results = [];
    for (i = 0, len = tableRecords.length; i < len; i++) {
      record = tableRecords[i];
      if ((record != null ? record.id : void 0) === id) {
        idToDelete = (await DB.getSnapshotKey(tableName, record, 'id'));
        results.push(remove(child(dbRef, `${tableName}/${idToDelete}/`)));
      } else {
        results.push(void 0);
      }
    }
    return results;
  }
};

// Error handling can be added here if needed

//# sourceMappingURL=calendarManager.js.map
