// Generated by CoffeeScript 2.7.0
var CalendarManager;

import DB from "@db";

import "../prototypes";

import {
  child,
  getDatabase,
  ref,
  remove,
  set
} from 'firebase/database';

import Manager from "./manager";

import {
  formatFileName,
  formatNameFirstNameOnly,
  formatTitleWords,
  getFirstWord,
  isAllUppercase,
  removeFileExtension,
  removeSpacesAndLowerCase,
  spaceBetweenWords,
  stringHasNumbers,
  toCamelCase,
  uppercaseFirstLetterOfAllWords,
  wordCount
} from "../globalFunctions";

import DatasetManager from "./datasetManager";

import LogManager from "./logManager";

export default CalendarManager = {
  formatEventTitle: (title) => {
    if (title && title.length > 0) {
      title = uppercaseFirstLetterOfAllWords(title);
      title = formatTitleWords(title);
      return title;
    }
  },
  addMultipleCalEvents: async function(currentUser, newEvents) {
    var currentEvents, dbRef, error, merged;
    dbRef = ref(getDatabase());
    currentEvents = (await DB.getTable(DB.tables.calendarEvents));
    if (!Array.isArray(newEvents)) {
      newEvents = [newEvents];
    }
    newEvents = DatasetManager.getUniqueArrayByProp(newEvents, "startDate", "startDate");
    merged = DatasetManager.mergeMultiple([currentEvents, newEvents]);
    try {
      return (await set(child(dbRef, `${DB.tables.calendarEvents}`), merged));
    } catch (error1) {
      error = error1;
      return LogManager.log(error.message, LogManager.logTypes.error, error.stack);
    }
  },
  setHolidays: async function(holidays) {
    var currentEvents, dbRef, error, eventsToAdd;
    dbRef = ref(getDatabase());
    currentEvents = (await DB.getTable(DB.tables.calendarEvents));
    eventsToAdd = [...currentEvents, ...holidays].filter(function(x) {
      return x != null;
    }).flat();
    try {
      return (await set(child(dbRef, `${DB.tables.calendarEvents}`), eventsToAdd));
    } catch (error1) {
      error = error1;
      return LogManager.log(error.message, LogManager.logTypes.error, error.stack);
    }
  },
  addCalendarEvent: async function(data) {
    var currentEvents, dbRef, error;
    dbRef = ref(getDatabase());
    currentEvents = Manager.convertToArray((await DB.getTable(DB.tables.calendarEvents)));
    currentEvents = currentEvents.filter(function(n) {
      return n;
    });
    try {
      return set(child(dbRef, `${DB.tables.calendarEvents}`), [...currentEvents, data]);
    } catch (error1) {
      error = error1;
      return LogManager.log(error.message, LogManager.logTypes.error, error.stack);
    }
  },
  deleteMultipleEvents: async function(events, currentUser) {
    var dbRef, holiday, i, idToDelete, len, results, tableRecords, userHolidays;
    dbRef = ref(getDatabase());
    tableRecords = Manager.convertToArray((await DB.getTable(DB.tables.calendarEvents)));
    userHolidays = tableRecords.filter((x) => {
      return x.phone === currentUser.phone && x.isHoliday === true;
    });
    results = [];
    for (i = 0, len = userHolidays.length; i < len; i++) {
      holiday = userHolidays[i];
      idToDelete = (await DB.getSnapshotKey(DB.tables.calendarEvents, holiday, 'id'));
      results.push((await remove(child(dbRef, `${DB.tables.calendarEvents}/${idToDelete}/`))));
    }
    return results;
  },
  deleteEvent: async function(tableName, id) {
    var dbRef, error, i, idToDelete, len, record, results, tableRecords;
    dbRef = ref(getDatabase());
    idToDelete = null;
    tableRecords = Manager.convertToArray((await DB.getTable(tableName)));
    results = [];
    for (i = 0, len = tableRecords.length; i < len; i++) {
      record = tableRecords[i];
      if ((record != null ? record.id : void 0) === id) {
        idToDelete = (await DB.getSnapshotKey(tableName, record, 'id'));
        try {
          results.push(remove(child(dbRef, `${tableName}/${idToDelete}/`)));
        } catch (error1) {
          error = error1;
          results.push(LogManager.log(error.message, LogManager.logTypes.error, error.stack));
        }
      } else {
        results.push(void 0);
      }
    }
    return results;
  }
};

//# sourceMappingURL=calendarManager.js.map
