// Generated by CoffeeScript 2.7.0
var DomManager;

import Manager from "./manager";

DomManager = {
  toggleActive: function(element) {
    if (element.classList.contains("active")) {
      return element.classList.remove("active");
    } else {
      return element.classList.add('active');
    }
  },
  toggleAnimateClass: function(element) {
    if (element.classList.contains("animate")) {
      return element.classList.remove("animate");
    } else {
      return element.classList.add('animate');
    }
  },
  hasClass: function(element, className) {
    if (!element) {
      return false;
    }
    if (element.classList.contains(className)) {
      return true;
    } else {
      return false;
    }
  },
  isMobile: function() {
    return window.screen.width < 801;
  },
  tapOrClick: function(isUppercase = false) {
    if (!isUppercase) {
      if (DomManager.isMobile()) {
        return "tap";
      }
      return "click";
    } else {
      if (DomManager.isMobile()) {
        return "Tap";
      }
      return "Click";
    }
  },
  debounce: function(callback, delay) {
    var executedFunction, timeout;
    timeout = null;
    executedFunction = function() {
      var later;
      later = function() {
        clearTimeout(timeout);
        return callback();
      };
      clearTimeout(timeout);
      return timeout = setTimeout(later, delay);
    };
    return executedFunction;
  },
  isInViewport: function(el) {
    var rect;
    if (Manager.isValid(el)) {
      rect = el.getBoundingClientRect();
      return rect.top >= 0 && rect.left >= 0 && rect.bottom <= (window.innerHeight || document.documentElement.clientHeight) && rect.right <= (window.innerWidth || document.documentElement.clientWidth);
    }
  },
  showInputLabels: function(wrapperClass) {
    var i, input, inputs, labelWrapper, len, parent, results;
    inputs = wrapperClass.querySelectorAll('input,textarea');
    results = [];
    for (i = 0, len = inputs.length; i < len; i++) {
      input = inputs[i];
      if (input) {
        if (input.value.length > 0 || (input != null ? input.textContent.length : void 0) > 0) {
          if (!input.classList.contains("react-toggle-screenreader-only")) {
            if (!input.classList.contains("MuiBase-input")) {
              parent = input.parentNode;
              if (parent) {
                parent.classList.add('active');
                labelWrapper = parent.querySelector("#label-wrapper");
                if (labelWrapper) {
                  results.push(labelWrapper.classList.add("active"));
                } else {
                  results.push(void 0);
                }
              } else {
                results.push(void 0);
              }
            } else {
              results.push(void 0);
            }
          } else {
            results.push(void 0);
          }
        } else {
          results.push(void 0);
        }
      } else {
        results.push(void 0);
      }
    }
    return results;
  },
  mostIsInViewport: function(scrollWrapper, el) {
    var pxCloseToEl, rect, scrollWrapperHeight;
    if (Manager.isValid(el)) {
      rect = el.getBoundingClientRect();
      scrollWrapperHeight = scrollWrapper.getBoundingClientRect().height;
      pxCloseToEl = rect.top - scrollWrapperHeight;
      return pxCloseToEl <= -170;
    }
  },
  addScrollListener: function(scrollableElement, callback, delay) {
    return scrollableElement.addEventListener('scroll', DomManager.debounce(function() {
      return callback();
    }, delay));
  },
  getSelectionText: function() {
    var text;
    text = "";
    if (window.getSelection != null) {
      text = window.getSelection().toString();
    } else if ((document.selection != null) && document.selection.type !== "Control") {
      text = document.selection.createRange().text;
    }
    return text;
  }
};

export default DomManager;
