// Generated by CoffeeScript 2.7.0
var DomManager;

import Manager from "./manager";

DomManager = {
  hasClass: function(element, className) {
    if (!element) {
      return false;
    }
    if (element.classList.contains(className)) {
      return true;
    } else {
      return false;
    }
  },
  isInViewport: function(el) {
    var rect;
    if (Manager.isValid(el)) {
      rect = el.getBoundingClientRect();
      return rect.top >= 0 && rect.left >= 0 && rect.bottom <= (window.innerHeight || document.documentElement.clientHeight) && rect.right <= (window.innerWidth || document.documentElement.clientWidth); // or $(window).width()
    }
  }
};

export default DomManager;

//# sourceMappingURL=domManager.js.map
