// Generated by CoffeeScript 2.7.0
var EmailManager, apiKey;

import emailjs from '@emailjs/browser';

apiKey = process.env.REACT_EMAILJS_API_KEY;

EmailManager = {
  Templates: {
    newActivity: "newActivity",
    featureRequest: 'featureRequest',
    appFeedback: 'appFeedback',
    customerSupport: 'customerSupport'
  },
  GetConfig: function(message, templateName, fromName) {
    var config;
    config = {
      service_id: 'service_ml9j8d3',
      template_id: templateName,
      user_id: apiKey,
      message: message,
      reply_to: 'support@peaceful-coparenting.app',
      from_name: fromName
    };
    return config;
  },
  SendEmail: function(templateName, message, fromName) {
    var config;
    config = EmailManager.GetConfig();
    config.template_id = templateName;
    config.message = message;
    config.from_name = fromName;
    return emailjs.send(config.service_id, config.template_id, config);
  },
  SendFeatureRequest: function(userEmail) {
    return EmailManager.SendEmail(EmailManager.Templates.featureRequest, "New Feature Request", userEmail);
  },
  SendAppFeedback: function(userEmail) {
    return EmailManager.SendEmail(EmailManager.Templates.appFeedback, "New Feedback", userEmail);
  },
  SendSupportEmail: function(userEmail) {
    return EmailManager.SendEmail(EmailManager.Templates.customerSupport, "App Support", userEmail);
  }
};

export default EmailManager;

//# sourceMappingURL=emailManager.js.map
