// Generated by CoffeeScript 2.7.0
var EmailManager, apiKey;

import emailjs from '@emailjs/browser';

apiKey = process.env.REACT_EMAILJS_API_KEY;

EmailManager = {
  Templates: {
    newActivity: "newActivity",
    featureRequest: 'featureRequest',
    appFeedback: 'appFeedback',
    customerSupport: 'customerSupport',
    emailVerification: 'emailVerification',
    coparentInvitation: 'coparent-invitation',
    parentInvitation: 'parent-invitation'
  },
  GetConfig: function(message, templateName, fromName) {
    var config;
    config = {
      service_id: 'service_ml9j8d3',
      template_id: templateName,
      user_id: apiKey,
      message: message,
      reply_to: 'support@peaceful-coparenting.app',
      from_name: fromName
    };
    return config;
  },
  SendEmail: function(templateName, message, userEmail) {
    var config;
    config = EmailManager.GetConfig();
    config.template_id = templateName;
    config.message = message;
    config.from_name = userEmail;
    return emailjs.send(config.service_id, config.template_id, config);
  },
  SendEmailToUser: function(templateName, message, userEmail, fromName) {
    var config;
    config = EmailManager.GetConfig();
    config.template_id = "coparent-invitation";
    config.message = message;
    config.from_name = fromName;
    return emailjs.send('default_service', templateName, {
      to_email: userEmail,
      from_name: fromName
    }).then(function(response) {
      return console.log('SUCCESS!', response.status, response.text);
    });
  },
  SendFeatureRequest: function(userEmail, message) {
    return EmailManager.SendEmail(EmailManager.Templates.featureRequest, message, userEmail);
  },
  SendAppFeedback: function(userEmail, message) {
    return EmailManager.SendEmail(EmailManager.Templates.appFeedback, message, userEmail);
  },
  SendSupportEmail: function(userEmail, message) {
    return EmailManager.SendEmail(EmailManager.Templates.customerSupport, message, userEmail);
  },
  SendEmailVerification: function(userEmail, message) {
    return EmailManager.SendEmailToUser(EmailManager.Templates.emailVerification, message, userEmail);
  }
};

export default EmailManager;

//# sourceMappingURL=emailManager.js.map
