// Generated by CoffeeScript 2.7.0
var ExpenseManager;

import DB from "../database/DB";

import {
  getDatabase,
  ref,
  update
} from 'firebase/database';

import LogManager from "./logManager";

import SecurityManager from "./securityManager";

export default ExpenseManager = {
  markAsPaid: async function(currentUser, updatedExpense, id) {
    var dbRef, error, expense, expenses, key, ownerKey;
    dbRef = getDatabase();
    key = null;
    try {
      expenses = (await SecurityManager.getExpenses(currentUser));
      expense = (await DB.find(expenses, ["id", id], false));
      ownerKey = expense.ownerKey;
      console.log(`${DB.tables.expenses}/${ownerKey}`);
      key = (await DB.getSnapshotKey(`${DB.tables.expenses}/${ownerKey}`, expense, "id"));
      return update(ref(dbRef, `${DB.tables.expenses}/${ownerKey}/${key}`), updatedExpense);
    } catch (error1) {
      error = error1;
      return LogManager.Log(error.message, LogManager.LogTypes.error, error.stack);
    }
  },
  UpdateExpense: async function(currentUserKey, updateIndex, updatedExpense) {
    var dbRef, error;
    dbRef = getDatabase();
    try {
      if (updateIndex) {
        return (await update(ref(dbRef, `${DB.tables.expenses}/${currentUserKey}/${updateIndex}`), updatedExpense));
      }
    } catch (error1) {
      error = error1;
      return LogManager.Log(error.message, LogManager.LogTypes.error, error.stack);
    }
  }
};

//# sourceMappingURL=expenseManager.js.map
