// Generated by CoffeeScript 2.7.0
var ExpenseManager

import {getDatabase} from "firebase/database"
import DB from "../database/DB"

import LogManager from "./logManager"

export default ExpenseManager = {
      UpdateExpense: async function (path, updatedExpense) {
            var dbRef, error
            dbRef = getDatabase()
            try {
                  if (path && updatedExpense) {
                        return await DB.ReplaceEntireRecord(path, updatedExpense)
                  }
            } catch (error1) {
                  error = error1
                  return LogManager.Log(error.message, LogManager.LogTypes.error, error.stack)
            }
      },
}

//# sourceMappingURL=expenseManager.js.map