// Generated by CoffeeScript 2.7.0
var InvitationManager

import {child, getDatabase, ref, set} from 'firebase/database'
import DB from '../database/DB'

import DatasetManager from './datasetManager'

import LogManager from './logManager'

import Manager from './manager'

export default InvitationManager = {
    AddInvitation: async function (invitation, currentUserKey) {
        var dbRef, error, existingInvitations, tableData
        try {
            dbRef = ref(getDatabase())
            tableData = []
            existingInvitations = await DB.getTable(`${DB.tables.invitations}/${currentUserKey}`)
            if (Manager.IsValid(existingInvitations)) {
                if (Manager.IsValid(existingInvitations)) {
                    tableData = DatasetManager.AddToArray(existingInvitations, invitation)
                } else {
                    tableData = [invitation]
                }
            } else {
                tableData = [invitation]
            }
            return await set(child(dbRef, `${DB.tables.invitations}/${currentUserKey}`), tableData)
        } catch (error1) {
            error = error1
            return LogManager.Log(error.message, LogManager.LogTypes.error, error.stack)
        }
    },
    RemoveInvitation: async function (id) {
        var error
        try {
            if (Manager.IsValid(id)) {
                return await DB.Delete(`${DB.tables.invitations}/${id}`)
            }
        } catch (error1) {
            error = error1
            return LogManager.Log(error.message, LogManager.LogTypes.error, error.stack)
        }
    },
}

//# sourceMappingURL=invitationManager.js.map