// Generated by CoffeeScript 2.7.0
var LoginManager, app, auth;

import {
  getAuth,
  signOut
} from "firebase/auth";

import {
  initializeApp
} from "firebase/app";

import firebaseConfig from "../firebaseConfig";

import LogManager from "./logManager";

app = initializeApp(firebaseConfig);

auth = getAuth(app);

LoginManager = {
  GetAuth: function() {
    return getAuth(app);
  },
  SignOut: function() {
    return signOut(auth).then(function() {
      //Sign-out successful.
      console.log('User signed out manually');
      return window.location.reload();
    }).catch(function(error) {
      //An error happened.
      LogManager.Log(`Error: ${error} | Code File: LoginManager | Function: SignOut`);
      return console.log(error);
    });
  }
};

export default LoginManager;

//# sourceMappingURL=LoginManager.js.map
