// Generated by CoffeeScript 2.7.0
var LogManager;

import * as Sentry from '@sentry/react';

LogManager = {
  LogTypes: {
    error: 'Error',
    warning: 'Warning',
    fatal: 'Fatal'
  },
  Log: function(message, type = LogManager.LogTypes.error, stackTrace) {
    if (!!window.location.href.includes('localhost')) {
      return Sentry.captureException(`Error: ${message} | Type: ${type} | Stacktrace: ${stackTrace}`);
    }
  }
};

export default LogManager;

//# sourceMappingURL=logManager.js.map
