// Generated by CoffeeScript 2.7.0
var LogManager

LogManager = {
  logTypes: {
    error: 'Error',
    warning: 'Warning',
    fatal: 'Fatal',
  },
  log: function (message, type, stackTrace) {
    var requestOptions
    requestOptions = {
      mode: 'no-cors',
      redirect: 'follow',
    }
    //fetch("https://peaceful-coparenting.app:5000/log?errorMessage=#{message}&messageType=#{type}&stackTrace=#{stackTrace}", requestOptions)
    console.log(message)
    return fetch(`https://peaceful-coparenting.app:5000/log?errorMessage=${message}&messageType=${type}`, requestOptions)
  },
}

export default LogManager

//# sourceMappingURL=logManager.js.map
