// Generated by CoffeeScript 2.7.0
var NotificationManager;

import {
  child,
  get,
  getDatabase,
  ref
} from 'firebase/database';

import DB from '@db';

import PushAlertApi from '@api/pushAlert';

export default NotificationManager = {
  getUserSubId: async(userPhone) => {
    var dbRef, subId;
    dbRef = ref(getDatabase());
    subId = '';
    return (await get(child(dbRef, `${DB.tables.pushAlertSubscribers}`)).then(function(snapshot) {
      var _subId;
      _subId = snapshot.val();
      return subId = _subId[userPhone];
    }));
  },
  getUserSubIdFromApi: (userPhone) => {
    var subId;
    subId = '';
    fetch(`https://peaceful-coparenting.app:5000/firebase/getSubId?phoneNumber=${'3307494534'}`).then(function(response) {
      return response.text();
    }).then(function(response) {
      subId = response;
      return console.log(response);
    });
    return subId;
  },
  sendToShareWith: async(coparentPhones, title, message) => {
    var i, len, phone, results, subId;
    results = [];
    for (i = 0, len = coparentPhones.length; i < len; i++) {
      phone = coparentPhones[i];
      subId = (await NotificationManager.getUserSubId(phone));
      results.push((await PushAlertApi.sendMessage(title, message, subId)));
    }
    return results;
  }
};

//# sourceMappingURL=notificationManager.js.map
