// Generated by CoffeeScript 2.7.0
var ObjectManager;

import ModelNames from "../models/modelNames";

import CalendarEvent from "../models/calendarEvent";

import Expense from "../models/expense";

import Memory from "../models/memory";

import TransferChangeRequest from "../models/transferChangeRequest";

import SwapRequest from "../models/swapRequest";

import InputSuggestion from "../models/inputSuggestion";

import User from "../models/user";

import Coparent from "../models/coparent";

import ChatThread from "../models/chat/chatThread";

import ChatMessage from "../models/chat/chatMessage";

import ChildUser from "../models/child/childUser";

import Doc from "../models/doc";

import Child from "../models/child/child";

import _ from "lodash";

import Parent from "../models/parent";

import Manager from "./manager";

ObjectManager = {
  RecursivelyFindProperty: function(obj, key) {
    var prop, result;
    if (Manager.isValid(obj) && typeof obj === 'object') {
      if (obj.hasOwnProperty(key)) {
        return obj[key];
      }
      for (prop in obj) {
        result = ObjectManager.RecursivelyFindProperty(obj[prop], key);
        if (result !== void 0) {
          return result;
        }
      }
    }
    return void 0;
  },
  cleanObject: function(object, modelName) {
    var prop, ref, ref1, returnObject;
    returnObject = (function() {
      switch (modelName) {
        case ModelNames.calendarEvent:
          return new CalendarEvent();
        case ModelNames.expense:
          return new Expense();
        case ModelNames.memory:
          return new Memory();
        case ModelNames.transferChangeRequest:
          return new TransferChangeRequest();
        case ModelNames.swapRequest:
          return new SwapRequest();
        case ModelNames.inputSuggestion:
          return new InputSuggestion();
        case ModelNames.user:
          return new User();
        case ModelNames.coparent:
          return new Coparent();
        case ModelNames.chatThread:
          return new ChatThread();
        case ModelNames.chatMessage:
          return new ChatMessage();
        case ModelNames.childUser:
          return new ChildUser();
        case ModelNames.child:
          return new Child();
        case ModelNames.parent:
          return new Parent();
        case ModelNames.doc:
          return new Doc();
      }
    })();
    for (prop in object) {
      if (Array.isArray(object[prop])) {
        if ((ref = object[prop]) === (void 0) || ref === null) {
          object[prop] = [];
        }
      } else {
        if (((ref1 = object[prop]) === (void 0) || ref1 === null) || object[prop].toString().toLowerCase().includes('invalid')) {
          object[prop] = '';
        }
      }
      returnObject[prop] = object[prop];
    }
    return returnObject;
  },
  merge: function(objectWithValuesToKeep, objectWithValuesToAdd) {
    return _.assign(objectWithValuesToKeep, objectWithValuesToAdd);
  },
  isEmpty: function(obj) {
    return _.isEmpty(obj);
  }
};

export default ObjectManager;

//# sourceMappingURL=objectManager.js.map
