// Generated by CoffeeScript 2.7.0
var SmsManager, apiKey;

import StringManager from "./stringManager";

apiKey = process.env.REACT_APP_SMS_API_KEY;

export default SmsManager = {
  lineBreak: '\r\n',
  signature: "\r\nThank You,\r\nPeaceful coParenting",
  Templates: {
    ParentChildVerification: function(childName, verificationCode) {
      return `${StringManager.uppercaseFirstLetterOfAllWords(childName)} is requesting sharing access. ${SmsManager.lineBreak}${SmsManager.lineBreak}If you would like to grant access, please share this code with them: ${verificationCode} ${SmsManager.lineBreak}${SmsManager.signature}`;
    },
    Invitation: function(currentUser, userName, recipientPhone) {
      return `Hello ${userName},${SmsManager.lineBreak}${SmsManager.lineBreak} You have been invited to join Peaceful coParenting by ${currentUser != null ? currentUser.name : void 0}. To accept the invite please visit ${SmsManager.lineBreak}https://peaceful-coparenting.app?type=invite&senderKey=${currentUser != null ? currentUser.key : void 0} ${SmsManager.lineBreak}  ${SmsManager.lineBreak}${SmsManager.signature}`;
    }
  },
  GetRemainingBalance: async function() {
    var error, requestOptions, response, result;
    requestOptions = {
      method: 'GET',
      redirect: 'follow'
    };
    try {
      response = (await fetch('https://peaceful-coparenting.app:5000/messaging/GetTextBalance', requestOptions));
      result = (await response.text());
      console.log(result);
      return result;
    } catch (error1) {
      error = error1;
      return console.error(error);
    }
  },
  Send: async function(phoneNumber, message) {
    var error, formData, requestOptions, response, result;
    console.log('sent');
    formData = new FormData();
    formData.append('phone', phoneNumber);
    formData.append('message', message);
    formData.append('key', apiKey);
    requestOptions = {
      method: 'POST',
      body: formData,
      mode: 'no-cors',
      redirect: 'follow'
    };
    try {
      response = (await fetch('https://peaceful-coparenting.app:5000/messaging/sendSms', requestOptions));
      result = (await response.text());
      return console.log(result);
    } catch (error1) {
      error = error1;
      return console.error(error);
    }
  }
};

//# sourceMappingURL=smsManager.js.map
