// Generated by CoffeeScript 2.7.0
var StringManager;

StringManager = {
  getReadablePhoneNumber: function(phoneNumber) {
    var cleaned, formattedPhone, match;
    formattedPhone = phoneNumber;
    cleaned = ('' + phoneNumber).replace(/\D/g, '');
    // Format the number with dashes
    match = cleaned.match(/^(\d{3})(\d{3})(\d{4})$/);
    if (match) {
      return `${match[1]}-${match[2]}-${match[3]}`;
    }
    return formattedPhone;
  },
  formatNameFirstNameOnly: function(name) {
    var returnString;
    if (!name) {
      return name;
    }
    returnString = name.toString();
    if (!returnString || returnString.length === 0) {
      return returnString;
    }
    returnString = returnString.split(' ')[0];
    return StringManager.uppercaseFirstLetterOfAllWords(returnString);
  },
  isAllUppercase: function(input) {
    return input === input.toUpperCase();
  },
  formatPhone: function(input) {
    input = input.toString().replace(/-/g, '').replace(/\s+/g, '').replace(/\(/g, '').replace(/\)/g, '').replace(/\+/g, '').replace(/\+1/g, '');
    return input;
  },
  getFileExtension: function(fileName) {
    return fileName.split('.').pop();
  },
  removeFileExtension: function(input) {
    return input.replace(/\.[^\/.]+$/, '');
  },
  wordCount: function(input) {
    return input.trim().split(/\s+/).length;
  },
  stringHasNumbers: function(input) {
    return /\d/.test(input);
  },
  capitalizeFirstWord: function(str) {
    var capitalizedFirstWord, firstWord;
    firstWord = str.split(' ')[0];
    capitalizedFirstWord = firstWord.charAt(0).toUpperCase() + firstWord.slice(1);
    return capitalizedFirstWord + str.slice(firstWord.length);
  },
  addSpaceBetweenWords: function(str) {
    str = str.replace(/([a-z])([A-Z])/, '$1 $2');
    return str;
  },
  getFirstWord: function(input) {
    return input.toString().replace(/ .*/, '');
  },
  uppercaseFirstLetterOfAllWords: function(input) {
    var words;
    words = input != null ? input.toString() : void 0;
    if (words && words !== void 0) {
      if ((words != null ? words.indexOf('-') : void 0) > -1) {
        words = input.replace(/-/g, ' ').split(' ');
      } else {
        words = words != null ? words.split(' ') : void 0;
      }
      words = words != null ? words.filter(function(x) {
        return x.length > 0;
      }) : void 0;
      words = words != null ? words.map(function(word) {
        return word[0].toUpperCase() + word.substr(1);
      }) : void 0;
      if ((words != null ? words.length : void 0) > 0) {
        words = words != null ? words.join(' ') : void 0;
      }
    }
    return words;
  },
  formatEventTitle: function(title) {
    if (title && title.length > 0) {
      title = StringManager.uppercaseFirstLetterOfAllWords(title);
      title = StringManager.formatTitleWords(title);
      return title;
    }
  },
  formatTitleWords: function(title) {
    return title = title.replaceAll("To", "to").replaceAll("Vs", "vs").replaceAll("With", "with").replaceAll("At", "at").replaceAll("From", "from").replaceAll("The", "the").replaceAll("And", "and").replaceAll("Is", "is").replaceAll("Not", "not");
  }
};

export default StringManager;

//# sourceMappingURL=stringManager.js.map
