// Generated by CoffeeScript 2.7.0
var UpdateManager;

import DB from "../database/DB";

import OneSignal from 'react-onesignal';

import Manager from "./manager.js";

import moment from "moment";

import DateFormats from "../constants/datetimeFormats";

import UpdateSubscriber from "../models/updateSubscriber";

import Update from "../models/new/update";

import LogManager from "./logManager";

import Apis from "../api/apis";

export default UpdateManager = {
  currentUser: null,
  lineBreak: '\r\n',
  // Define message templates
  templates: {
    // Template for event tomorrow reminder
    eventIsTomorrowReminder: function(event) {
      return `${event.title} is tomorrow ${Manager.IsValid(event.startTime) ? '@ ' + event.startTime : ''}`;
    },
    // Template for event in an hour reminder
    eventIsInAnHourReminder: function(event) {
      return `${event.title} is in 1 hour`;
    },
    // Template for event in half hour reminder
    eventIsInHalfHourReminder: function(event) {
      return `${event.title} is in 30 minutes`;
    },
    // Template for update reminder
    updateReminder: function() {
      return 'Visit New Updates in the menu to learn more';
    },
    // Template for swap request decision
    swapRequestApproval: function(request, recipientName) {
      return `Swap Request for ${moment(request != null ? request.startDate : void 0).format(DateFormats.readableMonthAndDay)} has been APPROVED by ${recipientName}${UpdateManager.lineBreak}${UpdateManager.lineBreak}`;
    },
    swapRequestRejection: function(request, recipientName) {
      return `Swap Request for ${moment(request != null ? request.startDate : void 0).format(DateFormats.readableMonthAndDay)} has been DECLINED.${UpdateManager.lineBreak}${UpdateManager.lineBreak} Reason: ${request.reason}. If you would still prefer to proceed with the request, please contact ${recipientName} to negotiate a potential agreement`;
    },
    transferRequestApproval: function(request, recipientName) {
      return `Transfer Change Request for ${moment(request != null ? request.startDate : void 0).format(DateFormats.readableMonthAndDay)} has been APPROVED by ${recipientName}${UpdateManager.lineBreak}${UpdateManager.lineBreak}`;
    },
    transferRequestRejection: function(request, recipientName) {
      return `Transfer Change Request for ${moment(request != null ? request.startDate : void 0).format(DateFormats.readableMonthAndDay)} has been DECLINED.${UpdateManager.lineBreak}${UpdateManager.lineBreak} Reason: ${request.declineReason}. If you would still prefer to proceed with the request, please contact ${recipientName} to negotiate a potential agreement`;
    }
  },
  //  PRODUCTION
  apiKey: process.env.REACT_APP_ONE_SIGNAL_API_KEY_DEV,
  appId: 'b243a232-3072-4fa8-9395-b1475054c531',
  // LOCALHOST
  //  apiKey: process.env.REACT_APP_ONE_SIGNAL_API_KEY_PROD
  //  appId: '4f864936-7169-4b17-acfa-ef403cbbafe8'
  init: function(currentUser) {
    var error;
    try {
      UpdateManager.currentUser = currentUser;
      window.OneSignalDeferred = window.OneSignalDeferred || [];
      return OneSignalDeferred.push(function() {
        return OneSignal.init({
          appId: UpdateManager.appId
        }).then(function() {
          return OneSignal.User.PushSubscription.addEventListener('change', UpdateManager.eventListener);
        });
      });
    } catch (error1) {
      error = error1;
      return LogManager.Log(`Error: ${error} | Code File:  | Function:  `);
    }
  },
  eventListener: function(event) {
    var error, newSubscriber, ref, subId, userSubscribed;
    userSubscribed = OneSignal.User.PushSubscription.optedIn;
    subId = event != null ? (ref = event.current) != null ? ref.id : void 0 : void 0;
    try {
      if (userSubscribed && subId) {
        newSubscriber = new UpdateSubscriber();
        return setTimeout(function() {
          var ref1, ref2;
          newSubscriber.email = UpdateManager != null ? (ref1 = UpdateManager.currentUser) != null ? ref1.email : void 0 : void 0;
          newSubscriber.key = UpdateManager != null ? (ref2 = UpdateManager.currentUser) != null ? ref2.key : void 0 : void 0;
          newSubscriber.id = Manager.GetUid();
          newSubscriber.subscriptionId = subId;
          return fetch(`https://api.onesignal.com/apps/${UpdateManager.appId}/subscriptions/${subId}/user/identity`).then(async function(identity) {
            var currentSubscribers, existingSubscriber, ref3, userIdentity;
            userIdentity = (await identity.json());
            currentSubscribers = (await DB.getTable(`${DB.tables.updateSubscribers}`));
            newSubscriber.oneSignalId = userIdentity != null ? (ref3 = userIdentity.identity) != null ? ref3.onesignal_id : void 0 : void 0;
            existingSubscriber = currentSubscribers != null ? currentSubscribers.find(function(x) {
              var ref4;
              return (x != null ? x.email : void 0) === (UpdateManager != null ? (ref4 = UpdateManager.currentUser) != null ? ref4.email : void 0 : void 0);
            }) : void 0;
            //              if existingSubscriber != null and existingSubscriber != undefined
            //                existingSubscriber.subscriptionId = subId
            //                existingSubscriber.oneSignalId = userIdentity?.identity?.onesignal_id
            //                index = DB.GetTableIndexById(currentSubscribers, existingSubscriber?.id)
            //                await DB.ReplaceEntireRecord("#{DB.tables.updateSubscribers}/#{index}", existingSubscriber)
            //              else
            if (!existingSubscriber) {
              return (await DB.Add(`${DB.tables.updateSubscribers}`, newSubscriber));
            }
          });
        }, 500);
      }
    } catch (error1) {
      error = error1;
      return LogManager.Log(`Error: ${error} | Code File:  | Function:  `);
    }
  },
  getUserSubId: async function(currentUserPhoneOrEmail, phoneOrEmail = "email") {
    var existingRecord;
    existingRecord = (await DB.find(DB.tables.updateSubscribers, [phoneOrEmail, currentUserPhoneOrEmail], true));
    return existingRecord != null ? existingRecord.subscriptionId : void 0;
  },
  deleteUser: function(oneSignalId, subId) {
    fetch(`https://api.onesignal.com/apps/${UpdateManager.appId}/subscriptions/${subId}`, {
      method: 'DELETE',
      headers: {
        'accept': 'application/json'
      }
    });
    return fetch(`https://api.onesignal.com/apps/${UpdateManager.appId}/users/by/onesignal_id/${oneSignalId}`, {
      method: 'DELETE'
    });
  },
  SendUpdate: async function(title, message, recipientKey, currentUser = null, category = '') {
    var allSubs, newNotification, raw, subId, subIdRecord;
    allSubs = (await DB.getTable(`${DB.tables.updateSubscribers}`));
    subIdRecord = allSubs.find(function(sub) {
      return sub.key === recipientKey;
    });
    if (!subIdRecord) {
      return false;
    }
    subId = subIdRecord != null ? subIdRecord.subscriptionId : void 0;
    raw = JSON.stringify({
      contents: {
        en: message
      },
      headings: {
        en: title
      },
      target_channel: "push",
      isAnyWeb: true,
      include_subscription_ids: [subId],
      app_id: UpdateManager.appId
    });
    // Add notification to database
    newNotification = new Update();
    newNotification.id = Manager.GetUid();
    newNotification.recipientKey = recipientKey;
    newNotification.ownerKey = currentUser != null ? currentUser.key : void 0;
    newNotification.sharedByName = currentUser != null ? currentUser.name : void 0;
    newNotification.title = title;
    newNotification.text = message;
    newNotification.category = category;
    await DB.Add(`${DB.tables.updates}/${recipientKey}`, [], newNotification);
    return (await Apis.OneSignal.SendUpdate(subId, raw));
  },
  SendToShareWith: async function(shareWithKeys, currentUser, title, message, category = '') {
    var i, key, len, results;
    if (Manager.IsValid(shareWithKeys)) {
      results = [];
      for (i = 0, len = shareWithKeys.length; i < len; i++) {
        key = shareWithKeys[i];
        results.push((await UpdateManager.SendUpdate(title, message, key, currentUser, category)));
      }
      return results;
    }
  },
  enableNotifications: function(subId) {
    var myHeaders, options, raw, url;
    myHeaders = new Headers();
    myHeaders.append("Accept", "application/json");
    myHeaders.append("Content-Type", "application/json");
    myHeaders.append("Authorization", `Basic ${UpdateManager.apiKey}`);
    url = `https://api.onesignal.com/apps/${UpdateManager.appId}/subscriptions/${subId}`;
    raw = JSON.stringify({
      "subscription": {
        "type": "Web Push",
        "enabled": true,
        "notification_types": 1
      }
    });
    options = {
      method: 'PATCH',
      headers: myHeaders,
      body: raw
    };
    return fetch(url, options).then(function(res) {
      return res.json();
    }).then(function(json) {
      return console.log(json);
    }).catch(function(err) {
      return console.error(err);
    });
  },
  disableNotifications: function(subId) {
    var myHeaders, options, raw, url;
    myHeaders = new Headers();
    myHeaders.append("Accept", "application/json");
    myHeaders.append("Content-Type", "application/json");
    myHeaders.append("Authorization", `Basic ${UpdateManager.apiKey}`);
    url = `https://api.onesignal.com/apps/${UpdateManager.appId}/subscriptions/${subId}`;
    raw = JSON.stringify({
      "subscription": {
        "type": "Web Push",
        "enabled": false,
        "notification_types": -31
      }
    });
    options = {
      method: 'PATCH',
      headers: myHeaders,
      body: raw
    };
    return fetch(url, options).then(function(res) {
      return res.json();
    }).then(function(json) {
      return console.log(json);
    }).catch(function(err) {
      return console.error(err);
    });
  }
};

//# sourceMappingURL=updateManager.js.map
