// Generated by CoffeeScript 2.7.0
var DadJokes

DadJokes = {
  getJoke: function () {
    return new Promise(function (resolve, reject) {
      console.log(false)
      return fetch(
        'https://api.api-ninjas.com/v1/dadjokes',
        {
          method: 'GET',
          headers: {
            'X-Api-Key': process.env.REACT_APP_DAD_JOKES_API_KEY,
          },
          contentType: 'application/json'.then(function (jokeResponse) {}),
        },
        jokeResponse.json().then(function (joke) {
          return resolve(joke[0].joke)
        })
      )
    })
  },
}

export default DadJokes

//# sourceMappingURL=dadJokes.js.map
