// Generated by CoffeeScript 2.7.0
// Import required modules
var PushAlertApi;

import NotificationManager from "../managers/notificationManager";

import Manager from "../managers/manager";

// Define PushAlertApi object
PushAlertApi = {
  // Define line break constant
  lineBreak: '\r\n',
  // Define message templates
  templates: {
    // Template for event tomorrow reminder
    eventIsTomorrowReminder: function(event) {
      return `${event.title} is tomorrow ${Manager.isValid(event.fromTime) ? '@ ' + event.fromTime : ''}`;
    },
    // Template for event in an hour reminder
    eventIsInAnHourReminder: function(event) {
      return `${event.title} is in 1 hour`;
    },
    // Template for event in half hour reminder
    eventIsInHalfHourReminder: function(event) {
      return `${event.title} is in 30 minutes`;
    },
    // Template for update reminder
    updateReminder: function() {
      return 'Visit New Updates in the menu to learn more';
    },
    // Template for swap request decision
    swapRequestDecision: function(request, decision) {
      return `A new Swap Request decision for ${request.fromDate} has been made by ${request.createdBy}${PushAlertApi.lineBreak}${PushAlertApi.lineBreak}Decision: ${decision}`;
    }
  },
  // Determine API URL based on environment
  apiUrl: function() {
    if (location.hostname === 'localhost') {
      return 'http://localhost:3002';
    } else {
      return 'https://www.peaceful-coparenting.com';
    }
  },
  // Send message to all users
  sendToAll: function(title, message) {
    return fetch('https://peaceful-coparenting.app:5000/messaging/sendToAll', {
      method: 'POST',
      mode: 'no-cors',
      body: JSON.stringify({
        title: title,
        message: message
      })
    });
  },
  // Subscribe a user to push notifications
  subscribeUser: function(userPhone) {
    var myHeaders, requestOptions, urlToUse;
    myHeaders = new Headers();
    myHeaders.append('Content-Type', 'application/json');
    myHeaders.append('Authorization', '461dafa18ed1684310b34ae8d00f746e');
    myHeaders.append('Access-Control-Allow-Origin', '*');
    urlToUse = 'https://api.pushalert.co/rest/v1/segment/38837/add';
    requestOptions = {
      method: 'POST',
      mode: 'no-cors',
      headers: myHeaders,
      body: JSON.stringify({
        subscibers: [userPhone]
      }),
      redirect: 'follow'
    };
    return fetch(urlToUse, requestOptions).then(function(result) {
      return console.log(result);
    }).catch(function(error) {
      return console.error(error);
    });
  },
  // Send a message to a specific user
  sendMessage: function(title, message, subId) {
    var myHeaders, requestOptions, subIdToUse, urlToUse, urlencoded;
    myHeaders = new Headers();
    myHeaders.append('Access-Control-Allow-Headers', 'Content-Type, x-requested-with');
    myHeaders.append('Access-Control-Allow-Origin', '*');
    subIdToUse = subId;
    urlToUse = 'https://peaceful-coparenting.app:5000/messaging/sendMessage';
    urlencoded = new URLSearchParams();
    urlencoded.append('title', title);
    urlencoded.append('url', 'https://www.peaceful-coparenting.com');
    urlencoded.append('message', message);
    urlencoded.append('subscriber', subIdToUse);
    requestOptions = {
      method: 'POST',
      mode: 'no-cors',
      headers: myHeaders,
      body: urlencoded,
      redirect: 'follow'
    };
    if (location.hostname !== "localhost") {
      return fetch(urlToUse, requestOptions).then(function(result) {
        return console.log(`Sent to: ${subIdToUse}`);
      }).catch(function(error) {
        return console.error(error);
      });
    } else {
      return fetch(urlToUse, requestOptions).then(function(result) {
        return console.log(`Sent to: ${subIdToUse}`);
      }).catch(function(error) {
        return console.error(error);
      });
    }
  },
  // Get subscriber ID for a user
  getSubId: async function(userPhone) {
    return (await NotificationManager.getUserSubId(userPhone));
  }
};

// Export PushAlertApi object
export default PushAlertApi;

//# sourceMappingURL=pushAlert.js.map
