// Generated by CoffeeScript 2.7.0
var Contact

import Manager from './managers/manager'

import moment from 'moment'

import DatetimeFormats from '../../constants/datetimeFormats'

Contact = class Contact {
  constructor(options = {}) {
    var ref, ref1, ref2, ref3, ref4, ref5, ref6, ref7, ref8
    this.id = Manager.GetUid()
    this.name = (ref = options != null ? options.name : void 0) != null ? ref : ''
    this.creationDate = moment().format(DatetimeFormats.dateForDb)
    this.email = (ref1 = options != null ? options.email : void 0) != null ? ref1 : ''
    this.phone = (ref2 = options != null ? options.phone : void 0) != null ? ref2 : ''
    this.address = (ref3 = options != null ? options.address : void 0) != null ? ref3 : ''
    this.accountType = (ref4 = options != null ? options.accountType : void 0) != null ? ref4 : ''
    this.parentType = (ref5 = options != null ? options.parentType : void 0) != null ? ref5 : ''
    this.relationshipToMe = (ref6 = options != null ? options.relationshipToMe : void 0) != null ? ref6 : ''
    this.profilePic = (ref7 = options != null ? options.profilePic : void 0) != null ? ref7 : ''
    this.userKey = (ref8 = options != null ? options.userKey : void 0) != null ? ref8 : ''
  }
}

export default Contact

//# sourceMappingURL=contact.js.map