// Generated by CoffeeScript 2.7.0
var Coparent;

import Manager from "../../managers/manager";

Coparent = class Coparent {
  constructor(options = {}) {
    var ref, ref1, ref2, ref3, ref4, ref5, ref6, ref7;
    this.id = (ref = options.id) != null ? ref : Manager.GetUid();
    this.name = (ref1 = options.name) != null ? ref1 : '';
    this.parentType = (ref2 = options.parentType) != null ? ref2 : '';
    this.phone = (ref3 = options.phone) != null ? ref3 : '';
    this.userKey = (ref4 = options.userKey) != null ? ref4 : '';
    this.address = (ref5 = options.address) != null ? ref5 : '';
    this.relationshipToMe = (ref6 = options.relationshipToMe) != null ? ref6 : '';
    this.email = (ref7 = options.email) != null ? ref7 : '';
  }

};

export default Coparent;

//# sourceMappingURL=coparent.js.map
