// Generated by CoffeeScript 2.7.0
var Parent

import Manager from '../../managers/manager'

Parent = class Parent {
    constructor(options = {}) {
        var ref, ref1, ref2, ref3, ref4, ref5
        this.id = Manager.GetUid()
        this.userKey = (ref = options != null ? options.userKey : void 0) != null ? ref : ''
        this.name = (ref1 = options != null ? options.name : void 0) != null ? ref1 : ''
        this.email = (ref2 = options != null ? options.email : void 0) != null ? ref2 : ''
        this.phone = (ref3 = options != null ? options.phone : void 0) != null ? ref3 : ''
        this.address = (ref4 = options != null ? options.address : void 0) != null ? ref4 : ''
        this.parentType = (ref5 = options != null ? options.parentType : void 0) != null ? ref5 : ''
    }
}

export default Parent

//# sourceMappingURL=parent.js.map