// Generated by CoffeeScript 2.7.0
var User

import moment from "moment"

import DateFormats from "../../constants/datetimeFormats"
import Manager from "../../managers/manager"

User = class User {
    constructor(options = {}) {
        var ref,
            ref1,
            ref10,
            ref11,
            ref12,
            ref13,
            ref14,
            ref15,
            ref16,
            ref17,
            ref18,
            ref19,
            ref2,
            ref20,
            ref21,
            ref22,
            ref23,
            ref24,
            ref25,
            ref26,
            ref27,
            ref28,
            ref29,
            ref3,
            ref30,
            ref4,
            ref5,
            ref6,
            ref7,
            ref8,
            ref9
        this.id = Manager.GetUid()
        this.creationDate = moment().format(DateFormats.dateForDb)
        this.key = (ref = options != null ? options.key : void 0) != null ? ref : ""
        this.name = (ref1 = options != null ? options.name : void 0) != null ? ref1 : ""
        this.email = (ref2 = options != null ? options.email : void 0) != null ? ref2 : ""
        this.phone = (ref3 = options != null ? options.phone : void 0) != null ? ref3 : ""
        this.children = (ref4 = options != null ? options.children : void 0) != null ? ref4 : []
        this.coparents = (ref5 = options != null ? options.coparents : void 0) != null ? ref5 : []
        this.sharedDataUserKeys = (ref6 = options != null ? options.sharedDataUserKeys : void 0) != null ? ref6 : []
        this.mutedUserKeys = (ref7 = options != null ? options.mutedUserKeys : void 0) != null ? ref7 : []
        this.parentType = (ref8 = options != null ? options.parentType : void 0) != null ? ref8 : ""
        this.accountType = (ref9 = options != null ? options.accountType : void 0) != null ? ref9 : ""
        this.homeAddress = (ref10 = options != null ? options.homeAddress : void 0) != null ? ref10 : ""
        this.app = {
            currentVersion: 1,
        }
        this.location = {
            country: (ref11 = options != null ? ((ref12 = options.location) != null ? ref12.country : void 0) : void 0) != null ? ref11 : "",
            city: (ref13 = options != null ? ((ref14 = options.location) != null ? ref14.city : void 0) : void 0) != null ? ref13 : "",
            state: (ref15 = options != null ? ((ref16 = options.location) != null ? ref16.state : void 0) : void 0) != null ? ref15 : "",
            latitude: (ref17 = options != null ? ((ref18 = options.location) != null ? ref18.latitude : void 0) : void 0) != null ? ref17 : "",
            location: (ref19 = options != null ? ((ref20 = options.location) != null ? ref20.location : void 0) : void 0) != null ? ref19 : "",
            timezone: (ref21 = options != null ? ((ref22 = options.location) != null ? ref22.timezone : void 0) : void 0) != null ? ref21 : "",
        }
        this.settings = {
            theme: "light",
            notificationsEnabled: true,
        }
        this.dailySummaries = {
            morningSentDate: moment().format(DateFormats.dateForDb),
            eveningSentDate: moment().format(DateFormats.dateForDb),
            morningReminderSummaryHour: "10am",
            eveningReminderSummaryHour: "8pm",
        }
        this.visitation = {
            transferAddress:
                (ref23 = options != null ? ((ref24 = options.visitation) != null ? ref24.transferAddress : void 0) : void 0) != null ? ref23 : "",
            transferNavLink:
                (ref25 = options != null ? ((ref26 = options.visitation) != null ? ref26.transferNavLink : void 0) : void 0) != null ? ref25 : "",
            schedule: (ref27 = options != null ? ((ref28 = options.visitation) != null ? ref28.schedule : void 0) : void 0) != null ? ref27 : "",
            holidays: (ref29 = options != null ? ((ref30 = options.visitation) != null ? ref30.holidays : void 0) : void 0) != null ? ref29 : [],
        }
    }
}

export default User

//# sourceMappingURL=user.js.map