// Generated by CoffeeScript 2.7.0
var User

import moment from 'moment'

import DateFormats from '../../constants/datetimeFormats'
import Manager from '../../managers/manager'

User = class User {
    constructor(options = {}) {
        var ref,
            ref1,
            ref10,
            ref11,
            ref12,
            ref13,
            ref14,
            ref15,
            ref16,
            ref17,
            ref18,
            ref19,
            ref2,
            ref20,
            ref21,
            ref22,
            ref23,
            ref24,
            ref25,
            ref26,
            ref27,
            ref28,
            ref29,
            ref3,
            ref4,
            ref5,
            ref6,
            ref7,
            ref8,
            ref9
        this.id = Manager.GetUid()
        this.creationDate = moment().format(DateFormats.dateForDb)
        this.key = (ref = options != null ? options.key : void 0) != null ? ref : ''
        this.name = (ref1 = options != null ? options.name : void 0) != null ? ref1 : ''
        this.email = (ref2 = options != null ? options.email : void 0) != null ? ref2 : ''
        this.phone = (ref3 = options != null ? options.phone : void 0) != null ? ref3 : ''
        this.children = (ref4 = options != null ? options.children : void 0) != null ? ref4 : []
        this.coparents = (ref5 = options != null ? options.coparents : void 0) != null ? ref5 : []
        this.sharedDataUsers = (ref6 = options != null ? options.sharedDataUsers : void 0) != null ? ref6 : []
        this.parentType = (ref7 = options != null ? options.parentType : void 0) != null ? ref7 : ''
        this.accountType = (ref8 = options != null ? options.accountType : void 0) != null ? ref8 : ''
        this.homeAddress = (ref9 = options != null ? options.homeAddress : void 0) != null ? ref9 : ''
        this.app = {
            currentVersion: 1,
        }
        this.location = {
            country: (ref10 = options != null ? ((ref11 = options.location) != null ? ref11.country : void 0) : void 0) != null ? ref10 : '',
            city: (ref12 = options != null ? ((ref13 = options.location) != null ? ref13.city : void 0) : void 0) != null ? ref12 : '',
            state: (ref14 = options != null ? ((ref15 = options.location) != null ? ref15.state : void 0) : void 0) != null ? ref14 : '',
            latitude: (ref16 = options != null ? ((ref17 = options.location) != null ? ref17.latitude : void 0) : void 0) != null ? ref16 : '',
            location: (ref18 = options != null ? ((ref19 = options.location) != null ? ref19.location : void 0) : void 0) != null ? ref18 : '',
            timezone: (ref20 = options != null ? ((ref21 = options.location) != null ? ref21.timezone : void 0) : void 0) != null ? ref20 : '',
        }
        this.settings = {
            theme: 'light',
            notificationsEnabled: true,
        }
        this.dailySummaries = {
            morningSentDate: moment().format(DateFormats.dateForDb),
            eveningSentDate: moment().format(DateFormats.dateForDb),
            morningReminderSummaryHour: '10am',
            eveningReminderSummaryHour: '8pm',
        }
        this.visitation = {
            transferAddress:
                (ref22 = options != null ? ((ref23 = options.visitation) != null ? ref23.transferAddress : void 0) : void 0) != null ? ref22 : '',
            transferNavLink:
                (ref24 = options != null ? ((ref25 = options.visitation) != null ? ref25.transferNavLink : void 0) : void 0) != null ? ref24 : '',
            schedule: (ref26 = options != null ? ((ref27 = options.visitation) != null ? ref27.schedule : void 0) : void 0) != null ? ref26 : '',
            holidays: (ref28 = options != null ? ((ref29 = options.visitation) != null ? ref29.holidays : void 0) : void 0) != null ? ref28 : [],
        }
    }
}

export default User

//# sourceMappingURL=user.js.map