// Generated by CoffeeScript 2.7.0
var ChatBookmark;

ChatBookmark = class ChatBookmark {
  constructor(ownerKey = '', messageId = '') {
    this.ownerKey = ownerKey;
    this.messageId = messageId;
  }

};

export default ChatBookmark;

//# sourceMappingURL=chatBookmark.js.map
