// Generated by CoffeeScript 2.7.0
var ChatRecoveryRequest;

ChatRecoveryRequest = class ChatRecoveryRequest {
  constructor(id = '', members = [], timestamp = '', signatureImageUrl = '', createdBy = '', reason = '') {
    this.id = id;
    this.members = members;
    this.timestamp = timestamp;
    this.signatureImageUrl = signatureImageUrl;
    this.createdBy = createdBy;
    this.reason = reason;
  }

};

export default ChatRecoveryRequest;

//# sourceMappingURL=chatRecoveryRequest.js.map
