// Generated by CoffeeScript 2.7.0
var ChatBookmark;

ChatBookmark = class ChatBookmark {
  constructor(ownerPhone = '', messageId = '') {
    this.ownerPhone = ownerPhone;
    this.messageId = messageId;
  }

};

export default ChatBookmark;
