// Generated by CoffeeScript 2.7.0
var ChatThread, member;

import Manager from "../../managers/manager";

import DateFormats from "../../constants/datetimeFormats";

import moment from "moment";

member = {
  key: '',
  name: '',
  id: ''
};

export default ChatThread = class ChatThread {
  constructor(id = Manager.getUid(), members = [member], creationTimestamp = moment().format(DateFormats.dateForDb), ownerKey = '', isPausedFor = []) {
    this.id = id;
    this.members = members;
    this.creationTimestamp = creationTimestamp;
    this.ownerKey = ownerKey;
    this.isPausedFor = isPausedFor;
  }

};

//# sourceMappingURL=chatThread.js.map
