// Generated by CoffeeScript 2.7.0
var ConversationMessage;

import Manager from "../../managers/manager";

export default ConversationMessage = class ConversationMessage {
  constructor(id = Manager.getUid(), sender = '', recipient = '', timestamp = '', message = '', recipientKey = '', senderKey = '') {
    this.id = id;
    this.sender = sender;
    this.recipient = recipient;
    this.timestamp = timestamp;
    this.message = message;
    this.recipientKey = recipientKey;
    this.senderKey = senderKey;
  }

};

//# sourceMappingURL=chatMessage.js.map
