// Generated by CoffeeScript 2.7.0
var ConversationMessage

import Manager from '../../managers/manager'

export default ConversationMessage = class ConversationMessage {
  constructor(id = Manager.getUid(), sender = '', recipient = '', timestamp = '', readState = 'delivered', message = '') {
    this.id = id
    this.sender = sender
    this.recipient = recipient
    this.timestamp = timestamp
    this.readState = readState
    this.message = message
  }
}

//# sourceMappingURL=chatMessage.js.map
