// Generated by CoffeeScript 2.7.0
var ChatThread;

import Manager from "../../managers/manager";

import DateFormats from "../../constants/dateFormats";

import moment from "moment";

export default ChatThread = class ChatThread {
  constructor(id = Manager.getUid(), members = [], creationTimestamp = moment().format(DateFormats.dateForDb), ownerPhone = '', isPausedFor = []) {
    this.id = id;
    this.members = members;
    this.creationTimestamp = creationTimestamp;
    this.ownerPhone = ownerPhone;
    this.isPausedFor = isPausedFor;
  }

};
