// Generated by CoffeeScript 2.7.0
var Chat

import moment from 'moment'

import DateFormats from '../../constants/datetimeFormats'
import Manager from '../../managers/manager'

Chat = class Chat {
    constructor(options = {}) {
        var ref, ref1, ref2
        this.id = Manager.GetUid()
        this.members = (ref = options != null ? options.members : void 0) != null ? ref : []
        this.creationDate = moment().format(DateFormats.dateForDb)
        this.ownerKey = (ref1 = options != null ? options.ownerKey : void 0) != null ? ref1 : ''
        this.isPausedFor = (ref2 = options != null ? options.isPausedFor : void 0) != null ? ref2 : []
    }
}

export default Chat

//# sourceMappingURL=chat.js.map