// Generated by CoffeeScript 2.7.0
var Chat, member;

import Manager from "../../managers/manager";

import DateFormats from "../../constants/datetimeFormats";

import moment from "moment";

member = {
  key: '',
  name: '',
  id: ''
};

Chat = class Chat {
  constructor(options = {}) {
    var ref, ref1;
    this.id = Manager.GetUid();
    this.members = [member];
    this.creationDate = moment().format(DateFormats.dateForDb);
    this.ownerKey = (ref = options != null ? options.ownerKey : void 0) != null ? ref : '';
    this.isPausedFor = (ref1 = options != null ? options.isPausedFor : void 0) != null ? ref1 : [];
  }

};

export default Chat;

//# sourceMappingURL=chat.js.map
