// Generated by CoffeeScript 2.7.0
var CalendarEvent

import Manager from '../../managers/manager'

CalendarEvent = class CalendarEvent {
    constructor(options = {}) {
        var ref,
            ref1,
            ref10,
            ref11,
            ref12,
            ref13,
            ref14,
            ref15,
            ref16,
            ref17,
            ref18,
            ref19,
            ref2,
            ref20,
            ref21,
            ref22,
            ref23,
            ref24,
            ref25,
            ref26,
            ref27,
            ref28,
            ref3,
            ref4,
            ref5,
            ref6,
            ref7,
            ref8,
            ref9
        // STRINGS
        this.id = Manager.GetUid()
        this.multipleDatesId = (ref = options != null ? options.multipleDatesId : void 0) != null ? ref : ''
        this.websiteUrl = (ref1 = options != null ? options.websiteUrl : void 0) != null ? ref1 : ''
        this.notes = (ref2 = options != null ? options.notes : void 0) != null ? ref2 : ''
        this.endDate = (ref3 = options != null ? options.endDate : void 0) != null ? ref3 : ''
        this.startDate = (ref4 = options != null ? options.startDate : void 0) != null ? ref4 : ''
        this.staticStartDate = (ref5 = options != null ? options.staticStartDate : void 0) != null ? ref5 : ''
        this.startTime = (ref6 = options != null ? options.startTime : void 0) != null ? ref6 : ''
        this.address = (ref7 = options != null ? options.address : void 0) != null ? ref7 : ''
        this.title = (ref8 = options != null ? options.title : void 0) != null ? ref8 : ''
        this.phone = (ref9 = options != null ? options.phone : void 0) != null ? ref9 : ''
        this.directionsLink = (ref10 = options != null ? options.directionsLink : void 0) != null ? ref10 : ''
        this.endTime = (ref11 = options != null ? options.endTime : void 0) != null ? ref11 : ''
        this.recurringInterval = (ref12 = options != null ? options.recurringInterval : void 0) != null ? ref12 : ''
        this.visitationPeriodEndDate = (ref13 = options != null ? options.visitationPeriodEndDate : void 0) != null ? ref13 : ''
        this.holidayName = (ref14 = options != null ? options.holidayName : void 0) != null ? ref14 : ''
        this.visitationSchedule = (ref15 = options != null ? options.visitationSchedule : void 0) != null ? ref15 : ''
        // OWNER
        this.owner = {
            name: (ref16 = options != null ? ((ref17 = options.owner) != null ? ref17.name : void 0) : void 0) != null ? ref16 : '',
            key: (ref18 = options != null ? ((ref19 = options.owner) != null ? ref19.key : void 0) : void 0) != null ? ref18 : '',
        }
        // ARRAYS
        this.reminderTimes = (ref20 = options != null ? options.reminderTimes : void 0) != null ? ref20 : []
        this.shareWith = (ref21 = options != null ? options.shareWith : void 0) != null ? ref21 : []
        this.children = (ref22 = options != null ? options.children : void 0) != null ? ref22 : []
        this.sentReminders = (ref23 = options != null ? options.sentReminders : void 0) != null ? ref23 : []
        // BOOLEANS
        this.fromVisitationSchedule = (ref24 = options != null ? options.fromVisitationSchedule : void 0) != null ? ref24 : false
        this.isHoliday = (ref25 = options != null ? options.isHoliday : void 0) != null ? ref25 : false
        this.isRecurring = (ref26 = options != null ? options.isRecurring : void 0) != null ? ref26 : false
        this.isCloned = (ref27 = options != null ? options.isCloned : void 0) != null ? ref27 : false
        this.isDateRange = (ref28 = options != null ? options.isDateRange : void 0) != null ? ref28 : false
    }
}

export default CalendarEvent

//# sourceMappingURL=calendarEvent.js.map