// Generated by CoffeeScript 2.7.0
var CalendarEvent;

import Manager from "../../managers/manager";

CalendarEvent = class CalendarEvent {
  constructor(options = {}) {
    var ref, ref1, ref10, ref11, ref12, ref13, ref14, ref15, ref16, ref17, ref18, ref19, ref2, ref20, ref21, ref3, ref4, ref5, ref6, ref7, ref8, ref9;
    // STRINGS
    this.id = Manager.GetUid();
    this.multipleDatesId = (ref = options.multipleDatesId) != null ? ref : '';
    this.websiteUrl = (ref1 = options.websiteUrl) != null ? ref1 : '';
    this.notes = (ref2 = options.notes) != null ? ref2 : '';
    this.endDate = (ref3 = options.endDate) != null ? ref3 : '';
    this.startDate = (ref4 = options.startDate) != null ? ref4 : '';
    this.staticStartDate = (ref5 = options.staticStartDate) != null ? ref5 : '';
    this.startTime = (ref6 = options.startTime) != null ? ref6 : '';
    this.ownerKey = (ref7 = options.ownerKey) != null ? ref7 : '';
    this.address = (ref8 = options.address) != null ? ref8 : '';
    this.title = (ref9 = options.title) != null ? ref9 : '';
    this.phone = (ref10 = options.phone) != null ? ref10 : '';
    this.createdBy = (ref11 = options.createdBy) != null ? ref11 : '';
    this.directionsLink = (ref12 = options.directionsLink) != null ? ref12 : '';
    this.endTime = (ref13 = options.endTime) != null ? ref13 : '';
    this.recurringInterval = (ref14 = options.recurringInterval) != null ? ref14 : '';
    this.visitationPeriodEndDate = (ref15 = options.visitationPeriodEndDate) != null ? ref15 : '';
    this.holidayName = (ref16 = options.holidayName) != null ? ref16 : '';
    this.visitationSchedule = (ref17 = options.visitationSchedule) != null ? ref17 : '';
    // ARRAYS
    this.GetReminderTimes = (ref18 = options.GetReminderTimes) != null ? ref18 : [];
    this.shareWith = (ref19 = options.shareWith) != null ? ref19 : [];
    this.children = (ref20 = options.children) != null ? ref20 : [];
    this.sentReminders = (ref21 = options.sentReminders) != null ? ref21 : [];
    // BOOLEANS
    this.fromVisitationSchedule = false;
    this.isHoliday = false;
    this.isRecurring = false;
    this.isCloned = false;
    this.isDateRange = false;
  }

};

export default CalendarEvent;

//# sourceMappingURL=calendarEvent.js.map
