// Generated by CoffeeScript 2.7.0
var Checklist;

import Manager from "../../managers/manager";

import moment from "moment";

import DatetimeFormats from "../../constants/datetimeFormats";

Checklist = class Checklist {
  constructor(options = {}) {
    var ref;
    this.id = Manager.GetUid();
    this.creationDate = moment().format(DatetimeFormats.dateForDb);
    this.items = (ref = options != null ? options.items : void 0) != null ? ref : [];
    this.fromOrTo = "from";
  }

};

export default Checklist;

//# sourceMappingURL=checklist.js.map
