// Generated by CoffeeScript 2.7.0
var Doc;

import Manager from "../../managers/manager";

import moment from "moment";

import DatetimeFormats from "../../constants/datetimeFormats";

Doc = class Doc {
  constructor(options = {}) {
    var ref, ref1, ref2, ref3, ref4, ref5;
    this.id = Manager.GetUid();
    this.creationDate = moment().format(DatetimeFormats.dateForDb);
    this.name = (ref = options != null ? options.name : void 0) != null ? ref : '';
    this.type = (ref1 = options != null ? options.type : void 0) != null ? ref1 : '';
    this.shareWith = (ref2 = options != null ? options.shareWith : void 0) != null ? ref2 : [];
    this.url = (ref3 = options != null ? options.url : void 0) != null ? ref3 : '';
    this.ownerKey = (ref4 = options != null ? options.ownerKey : void 0) != null ? ref4 : '';
    this.docText = (ref5 = options != null ? options.docText : void 0) != null ? ref5 : '';
  }

};

export default Doc;

//# sourceMappingURL=doc.js.map
