// Generated by CoffeeScript 2.7.0
var Doc

import moment from "moment"

import DatetimeFormats from "../../constants/datetimeFormats"
import Manager from "../../managers/manager"

Doc = class Doc {
      constructor(options = {}) {
            var ref, ref1, ref2, ref3, ref4, ref5, ref6, ref7, ref8
            this.id = Manager.GetUid()
            this.creationDate = moment().format(DatetimeFormats.dateForDb)
            this.documentName = (ref = options != null ? options.documentName : void 0) != null ? ref : ""
            this.type = (ref1 = options != null ? options.type : void 0) != null ? ref1 : ""
            this.shareWith = (ref2 = options != null ? options.shareWith : void 0) != null ? ref2 : []
            this.url = (ref3 = options != null ? options.url : void 0) != null ? ref3 : ""
            this.docText = (ref4 = options != null ? options.docText : void 0) != null ? ref4 : ""
            this.owner = {
                  name: (ref5 = options != null ? ((ref6 = options.owner) != null ? ref6.name : void 0) : void 0) != null ? ref5 : "",
                  key: (ref7 = options != null ? ((ref8 = options.owner) != null ? ref8.key : void 0) : void 0) != null ? ref7 : "",
            }
      }
}

export default Doc

//# sourceMappingURL=doc.js.map