// Generated by CoffeeScript 2.7.0
var Memory;

import DateFormats from "../../constants/datetimeFormats";

import moment from "moment";

import Manager from "../../managers/manager";

Memory = class Memory {
  constructor(options = {}) {
    var ref, ref1, ref2, ref3, ref4, ref5, ref6;
    this.id = Manager.GetUid();
    this.creationDate = moment().format(DateFormats.dateForDb);
    this.name = (ref = options != null ? options.name : void 0) != null ? ref : '';
    this.captureDate = (ref1 = options != null ? options.captureDate : void 0) != null ? ref1 : '';
    this.notes = (ref2 = options != null ? options.notes : void 0) != null ? ref2 : '';
    this.shareWith = (ref3 = options != null ? options.shareWith : void 0) != null ? ref3 : [];
    this.title = (ref4 = options != null ? options.title : void 0) != null ? ref4 : '';
    this.url = (ref5 = options != null ? options.url : void 0) != null ? ref5 : '';
    this.ownerKey = (ref6 = options != null ? options.ownerKey : void 0) != null ? ref6 : '';
  }

};

export default Memory;

//# sourceMappingURL=memory.js.map
