// Generated by CoffeeScript 2.7.0
var Update;

import DateFormats from "../../constants/datetimeFormats";

import moment from "moment";

import Manager from "../../managers/manager";

Update = class Update {
  constructor(options = {}) {
    var ref, ref1, ref2, ref3;
    this.id = Manager.GetUid();
    this.timestamp = moment().format(DateFormats.timestamp);
    this.category = (ref = options != null ? options.category : void 0) != null ? ref : '';
    this.recipientKey = (ref1 = options != null ? options.recipientKey : void 0) != null ? ref1 : '';
    this.ownerKey = (ref2 = options != null ? options.ownerKey : void 0) != null ? ref2 : '';
    this.title = (ref3 = options != null ? options.title : void 0) != null ? ref3 : '';
  }

};

export default Update;

//# sourceMappingURL=update.js.map
