// Generated by CoffeeScript 2.7.0
var Activity;

import DateFormats from "../constants/dateFormats";

import moment from "moment";

export default Activity = class Activity {
  constructor(id = '', dateCreated = moment().format(DateFormats.fullDatetime), category = '', recipientKey = '', ownerKey = '', title = '', text = '') {
    this.id = id;
    this.dateCreated = dateCreated;
    this.category = category;
    this.recipientKey = recipientKey;
    this.ownerKey = ownerKey;
    this.title = title;
    this.text = text;
  }

};

//# sourceMappingURL=activity.js.map
