// Generated by CoffeeScript 2.7.0
var ActivitySet

import DateFormats from '../constants/dateFormats'

import moment from 'moment'

export default ActivitySet = class ActivitySet {
  constructor(
    id = '',
    dateCreated = moment().format(DateFormats.fullDatetime),
    category = '',
    recipientPhone = '',
    creatorPhone = '',
    title = '',
    text = ''
  ) {
    this.id = id
    this.dateCreated = dateCreated
    this.category = category
    this.recipientPhone = recipientPhone
    this.creatorPhone = creatorPhone
    this.title = title
    this.text = text
  }
}

//# sourceMappingURL=activity.js.map