// Generated by CoffeeScript 2.7.0
var ActivityPriority;

ActivityPriority = {
  Critical: 'critical',
  Normal: 'normal'
};

export default ActivityPriority;

//# sourceMappingURL=activityPriority.js.map
