// Generated by CoffeeScript 2.7.0
var AppUpdate

import moment from 'moment'

import DatetimeFormats from '../constants/datetimeFormats'
import Manager from '../managers/manager'

AppUpdate = class AppUpdate {
    constructor(options = {}) {
        var ref, ref1
        this.id = Manager.GetUid()
        this.timestamp =
            (ref = moment(options.timestamp).format(DatetimeFormats.dateForDb)) != null ? ref : moment().format(DatetimeFormats.dateForDb)
        this.currentVersion = (ref1 = options.currentVersion) != null ? ref1 : 1
    }
}

export default AppUpdate

//# sourceMappingURL=appUpdate.js.map