// Generated by CoffeeScript 2.7.0
var CalendarEvent

import Manager from '../managers/manager'

export default CalendarEvent = class CalendarEvent {
  constructor(
    id = Manager.getUid(),
    websiteUrl = '',
    notes = '',
    shareWith = [],
    endDate = '',
    startDate = '',
    startTime = '',
    ownerPhone = '',
    children = [],
    location = '',
    title = '',
    phone = '',
    createdBy = '',
    reminderTimes = [],
    coparentsToRemindPhones = [],
    directionsLink = '',
    endTime = '',
    fromVisitationSchedule = false,
    repeatInterval = '',
    sentReminders = [],
    visitationPeriodEndDate = '',
    visibleToAll = false,
    holidayName = '',
    visitationSchedule = '',
    isHoliday = false,
    isRepeating = false,
    isCloned = false,
    isDateRange = false
  ) {
    this.id = id
    this.websiteUrl = websiteUrl
    this.notes = notes
    this.shareWith = shareWith
    this.endDate = endDate
    this.startDate = startDate
    this.startTime = startTime
    this.ownerPhone = ownerPhone
    this.children = children
    this.location = location
    this.title = title
    this.phone = phone
    this.createdBy = createdBy
    this.reminderTimes = reminderTimes
    this.coparentsToRemindPhones = coparentsToRemindPhones
    this.directionsLink = directionsLink
    this.endTime = endTime
    this.fromVisitationSchedule = fromVisitationSchedule
    this.repeatInterval = repeatInterval
    this.sentReminders = sentReminders
    this.visitationPeriodEndDate = visitationPeriodEndDate
    this.visibleToAll = visibleToAll
    this.holidayName = holidayName
    this.visitationSchedule = visitationSchedule
    this.isHoliday = isHoliday
    this.isRepeating = isRepeating
    this.isCloned = isCloned
    this.isDateRange = isDateRange
  }
}

//# sourceMappingURL=calendarEvent.js.map
