// Generated by CoffeeScript 2.7.0
var CalendarEvent;

export default CalendarEvent = class CalendarEvent {
  constructor(id = '', websiteUrl = '', notes = '', shareWith = [], endDate = '', startDate = '', startTime = '', ownerPhone = '', children = [], location = '', title = '', createdBy = '', reminderTimes = [], coparentsToRemindPhones = [], directionsLink = '', endTime = '', morningSummaryReminderSent = false, eveningSummaryReminderSent = false, fromVisitationSchedule = false, repeatInterval = '', sentReminders = [], visitationPeriodEndDate = '', isHoliday = false, holidayName = '', visitationSchedule = '') {
    this.id = id;
    this.websiteUrl = websiteUrl;
    this.notes = notes;
    this.shareWith = shareWith;
    this.endDate = endDate;
    this.startDate = startDate;
    this.startTime = startTime;
    this.ownerPhone = ownerPhone;
    this.children = children;
    this.location = location;
    this.title = title;
    this.createdBy = createdBy;
    this.reminderTimes = reminderTimes;
    this.coparentsToRemindPhones = coparentsToRemindPhones;
    this.directionsLink = directionsLink;
    this.endTime = endTime;
    this.morningSummaryReminderSent = morningSummaryReminderSent;
    this.eveningSummaryReminderSent = eveningSummaryReminderSent;
    this.fromVisitationSchedule = fromVisitationSchedule;
    this.repeatInterval = repeatInterval;
    this.sentReminders = sentReminders;
    this.visitationPeriodEndDate = visitationPeriodEndDate;
    this.isHoliday = isHoliday;
    this.holidayName = holidayName;
    this.visitationSchedule = visitationSchedule;
  }

};

//# sourceMappingURL=calendarEvent.js.map
