// Generated by CoffeeScript 2.7.0
var CalendarEvent;

export default CalendarEvent = class CalendarEvent {
  constructor(id = '', websiteUrl = '', notes = '', shareWith = [], toDate = '', fromDate = '', startTime = '', phone = '', children = [], location = '', title = '', createdBy = '', reminderTimes = [], directionsLink = '', endTime = '', morningSummaryReminderSent = false, eveningSummaryReminderSent = false, fromVisitationSchedule = false, repeatInterval = '', sentReminders = [], visitationPeriodEndDate = '', isHoliday = false) {
    this.id = id;
    this.websiteUrl = websiteUrl;
    this.notes = notes;
    this.shareWith = shareWith;
    this.toDate = toDate;
    this.fromDate = fromDate;
    this.startTime = startTime;
    this.phone = phone;
    this.children = children;
    this.location = location;
    this.title = title;
    this.createdBy = createdBy;
    this.reminderTimes = reminderTimes;
    this.directionsLink = directionsLink;
    this.endTime = endTime;
    this.morningSummaryReminderSent = morningSummaryReminderSent;
    this.eveningSummaryReminderSent = eveningSummaryReminderSent;
    this.fromVisitationSchedule = fromVisitationSchedule;
    this.repeatInterval = repeatInterval;
    this.sentReminders = sentReminders;
    this.visitationPeriodEndDate = visitationPeriodEndDate;
    this.isHoliday = isHoliday;
  }

};

//# sourceMappingURL=calendarEvent.js.map
