// Generated by CoffeeScript 2.7.0
var ChatRecoveryRequest;

export default ChatRecoveryRequest = class ChatRecoveryRequest {
  constructor(id = '', members = [], timestamp = '', signatureImageUrl = '', createdBy = '') {
    this.id = id;
    this.members = members;
    this.timestamp = timestamp;
    this.signatureImageUrl = signatureImageUrl;
    this.createdBy = createdBy;
  }

};

//# sourceMappingURL=chatRecoveryRequest.js.map
