// Generated by CoffeeScript 2.7.0
var Checklist;

import Manager from "/src/managers/manager";

export default Checklist = class Checklist {
  constructor(id = Manager.GetUid(), items = [], fromOrTo = "from") {
    this.id = id;
    this.items = items;
    this.fromOrTo = fromOrTo;
  }

};

//# sourceMappingURL=checklist.js.map
