// Generated by CoffeeScript 2.7.0
var Contact;

import Manager from "/src/managers/manager";

Contact = class Contact {
  constructor(id = Manager.GetUid(), name = '', email = '', phone = '', address = '', accountType = '', parentType = '', relationshipToMe = '', profilePic = '', userKey = '') {
    this.id = id;
    this.name = name;
    this.email = email;
    this.phone = phone;
    this.address = address;
    this.accountType = accountType;
    this.parentType = parentType;
    this.relationshipToMe = relationshipToMe;
    this.profilePic = profilePic;
    this.userKey = userKey;
  }

};

export default Contact;

//# sourceMappingURL=contact.js.map
