// Generated by CoffeeScript 2.7.0
var ConversationMessage;

import Manager from "../managers/manager";

export default ConversationMessage = class ConversationMessage {
  constructor(id = Manager.getUid(), bookmarks = [], sender = '', recipient = '', timestamp = '', readState = 'delivered', message = '') {
    this.id = id;
    this.bookmarks = bookmarks;
    this.sender = sender;
    this.recipient = recipient;
    this.timestamp = timestamp;
    this.readState = readState;
    this.message = message;
  }

};

//# sourceMappingURL=conversationMessage.js.map
