// Generated by CoffeeScript 2.7.0
var ConversationThread;

export default ConversationThread = class ConversationThread {
  constructor(id, members = [], timestamp = '', messages = [], threadOwner = '', threadVisibilityMembers = []) {
    this.id = id;
    this.members = members;
    this.timestamp = timestamp;
    this.messages = messages;
    this.threadOwner = threadOwner;
    this.threadVisibilityMembers = threadVisibilityMembers;
  }

};

//# sourceMappingURL=conversationThread.js.map
