// Generated by CoffeeScript 2.7.0
var ConversationThread

export default ConversationThread = class ConversationThread {
  constructor(id, members = [], timestamp = '', messages = [], firstMessageFrom = '') {
    this.id = id
    this.members = members
    this.timestamp = timestamp
    this.messages = messages
    this.firstMessageFrom = firstMessageFrom
  }
}
