// Generated by CoffeeScript 2.7.0
var ConversationMessageBookmark;

ConversationMessageBookmark = class ConversationMessageBookmark {
  constructor(ownerPhone = '', messageId = '') {
    this.ownerPhone = ownerPhone;
    this.messageId = messageId;
  }

};

export default ConversationMessageBookmark;

//# sourceMappingURL=conversationMessageBookmark.js.map
