// Generated by CoffeeScript 2.7.0
var ConversationMessage

import Manager from '../managers/manager'

export default ConversationMessage = class ConversationMessage {
  constructor(
    id = Manager.getUid(),
    saved = false,
    sender = '',
    recipient = '',
    timestamp = '',
    readState = 'delivered',
    message = '',
    notificationSent = false
  ) {
    this.id = id
    this.saved = saved
    this.sender = sender
    this.recipient = recipient
    this.timestamp = timestamp
    this.readState = readState
    this.message = message
    this.notificationSent = notificationSent
  }
}

//# sourceMappingURL=conversationMessage.js.map
