// Generated by CoffeeScript 2.7.0
var Coparent;

export default Coparent = class Coparent {
  constructor(name = '', parentType = '', phone = '', address = '', id = '') {
    this.name = name;
    this.parentType = parentType;
    this.phone = phone;
    this.address = address;
    this.id = id;
  }

};

//# sourceMappingURL=coparent.js.map
