// Generated by CoffeeScript 2.7.0
var Coparent;

Coparent = class Coparent {
  constructor(name = '', parentType = '', phone = '', userKey = '', address = '', id = '', relationshipToMe = '', email = '') {
    this.name = name;
    this.parentType = parentType;
    this.phone = phone;
    this.userKey = userKey;
    this.address = address;
    this.id = id;
    this.relationshipToMe = relationshipToMe;
    this.email = email;
  }

};

export default Coparent;

//# sourceMappingURL=coparent.js.map
