// Generated by CoffeeScript 2.7.0
var Doc;

import Manager from "../managers/manager";

export default Doc = class Doc {
  constructor(name = '', type = '', shareWith = [], url = '', id = Manager.getUid(), ownerKey = '', docText = '') {
    this.name = name;
    this.type = type;
    this.shareWith = shareWith;
    this.url = url;
    this.id = id;
    this.ownerKey = ownerKey;
    this.docText = docText;
  }

};

//# sourceMappingURL=doc.js.map
