// Generated by CoffeeScript 2.7.0
var Doc;

export default Doc = class Doc {
  constructor(name = '', type = '', shareWith = [], url = '', id = '', uploadedBy) {
    this.name = name;
    this.type = type;
    this.shareWith = shareWith;
    this.url = url;
    this.id = id;
    this.uploadedBy = uploadedBy;
  }

};

//# sourceMappingURL=doc.js.map
