// Generated by CoffeeScript 2.7.0
var DocumentHeader;

import Manager from "../managers/manager";

export default DocumentHeader = class DocumentHeader {
  constructor(id = Manager.GetUid(), headerText = '', ownerKey = '') {
    this.id = id;
    this.headerText = headerText;
    this.ownerKey = ownerKey;
  }

};

//# sourceMappingURL=documentHeader.js.map
