// Generated by CoffeeScript 2.7.0
var DocumentHeader;

import Manager from "../managers/manager";

DocumentHeader = class DocumentHeader {
  constructor(options = {}) {
    var ref, ref1;
    this.id = Manager.GetUid();
    this.headerText = (ref = options != null ? options.headerText : void 0) != null ? ref : '';
    this.ownerKey = (ref1 = options != null ? options.ownerKey : void 0) != null ? ref1 : '';
  }

};

export default DocumentHeader;

//# sourceMappingURL=documentHeader.js.map
