// Generated by CoffeeScript 2.7.0
var FormNames;

FormNames = {
  calendar: 'calendar',
  swapRequest: 'swapRequest',
  transferRequest: 'transferRequest',
  expense: 'expense',
  memories: "memories"
};

export default FormNames;

//# sourceMappingURL=formNames.js.map
