// Generated by CoffeeScript 2.7.0
(function() {
  var FormNames;

  FormNames = {
    calendar: 'calendar',
    swapRequest: 'swapRequest',
    transferRequest: 'transferRequest',
    expense: 'expense',
    memories: "memories"
  };

}).call(this);

//# sourceMappingURL=formNames.js.map
