// Generated by CoffeeScript 2.7.0
var InputSuggestion;

export default InputSuggestion = class InputSuggestion {
  constructor(ownerPhone = '', formName = '', suggestion = '', id = '') {
    this.ownerPhone = ownerPhone;
    this.formName = formName;
    this.suggestion = suggestion;
    this.id = id;
  }

};

//# sourceMappingURL=inputSuggestion.js.map
