// Generated by CoffeeScript 2.7.0
var InputSuggestion;

import Manager from "../managers/manager";

export default InputSuggestion = class InputSuggestion {
  constructor(ownerKey = '', formName = '', suggestion = '', id = Manager.getUid()) {
    this.ownerKey = ownerKey;
    this.formName = formName;
    this.suggestion = suggestion;
    this.id = id;
  }

};

//# sourceMappingURL=inputSuggestion.js.map
