// Generated by CoffeeScript 2.7.0
var Invitation;

import Manager from "../managers/manager";

import DatetimeFormats from "../constants/datetimeFormats";

import moment from "moment";

Invitation = class Invitation {
  constructor(options = {}) {
    var ref, ref1, ref2, ref3;
    this.id = Manager.GetUid();
    this.timestamp = (ref = moment(options != null ? options.timestamp : void 0).format(DatetimeFormats.dateForDb)) != null ? ref : moment().format(DatetimeFormats.dateForDb);
    this.senderKey = options != null ? options.senderKey : void 0;
    this.recipientPhone = (ref1 = options != null ? options.recipientPhone : void 0) != null ? ref1 : '';
    this.senderName = (ref2 = options != null ? options.senderName : void 0) != null ? ref2 : '';
    this.senderEmail = (ref3 = options != null ? options.senderEmail : void 0) != null ? ref3 : '';
    this.status = 'sent';
  }

};

export default Invitation;

//# sourceMappingURL=invisitation.js.map
