// Generated by CoffeeScript 2.7.0
var Memory

export default Memory = class Memory {
  constructor(id = '', creationDate = '', phone = '', memoryName = '', notes = '', shareWith = [], title = '', url = '', createdBy = '') {
    this.id = id
    this.creationDate = creationDate
    this.phone = phone
    this.memoryName = memoryName
    this.notes = notes
    this.shareWith = shareWith
    this.title = title
    this.url = url
    this.createdBy = createdBy
  }
}

//# sourceMappingURL=memory.js.map
