// Generated by CoffeeScript 2.7.0
var Memory;

export default Memory = class Memory {
  constructor(id = '', creationDate = '', memoryName = '', notes = '', shareWith = [], title = '', url = '', ownerPhone = '') {
    this.id = id;
    this.creationDate = creationDate;
    this.memoryName = memoryName;
    this.notes = notes;
    this.shareWith = shareWith;
    this.title = title;
    this.url = url;
    this.ownerPhone = ownerPhone;
  }

};

//# sourceMappingURL=memory.js.map
