// Generated by CoffeeScript 2.7.0
var ModelNames;

ModelNames = {
  calendarEvent: "calendarEvent",
  conversation: "conversation",
  coparent: 'coparent',
  expense: 'expense',
  memory: 'memory',
  swapRequest: 'swapRequest',
  titleSuggestion: 'titleSuggestion',
  user: "user",
  conversationMessage: 'conversationMessage'
};

export default ModelNames;

//# sourceMappingURL=modelNames.js.map
