// Generated by CoffeeScript 2.7.0
var ModelNames

ModelNames = {
  calendarEvent: 'calendarEvent',
  conversation: 'conversation',
  coparent: 'coparent',
  expense: 'expense',
  memory: 'memory',
  swapRequest: 'swapRequest',
  inputSuggestion: 'inputSuggestion',
  user: 'user',
  transferChangeRequest: 'transferChangeRequest',
  chatMessage: 'chatMessage',
  chatThread: 'chatThread',
  childUser: 'childUser',
  doc: 'doc',
  child: 'child',
}

export default ModelNames

//# sourceMappingURL=modelNames.js.map
