// Generated by CoffeeScript 2.7.0
var NotificationSubscribers;

export default NotificationSubscribers = class NotificationSubscribers {
  constructor(id = '', key = '', email = '', subscriptionId = '') {
    this.id = id;
    this.key = key;
    this.email = email;
    this.subscriptionId = subscriptionId;
  }

};

//# sourceMappingURL=notificationSubscriber.js.map
