// Generated by CoffeeScript 2.7.0
var Notification

import DateFormats from '../constants/datetimeFormats'

import moment from 'moment'

export default Notification = class Notification {
  constructor(
    id = '',
    creationDate = moment().format(DateFormats.fullDatetime),
    category = '',
    recipientKey = '',
    ownerKey = '',
    title = '',
    text = ''
  ) {
    this.id = id
    this.creationDate = creationDate
    this.category = category
    this.recipientKey = recipientKey
    this.ownerKey = ownerKey
    this.title = title
    this.text = text
  }
}

//# sourceMappingURL=notification.js.map