// Generated by CoffeeScript 2.7.0
var NotificationSubscribers;

export default NotificationSubscribers = class NotificationSubscribers {
  constructor(id = '', phone = '', email = '', subscriptionId = '', oneSignalId = '') {
    this.id = id;
    this.phone = phone;
    this.email = email;
    this.subscriptionId = subscriptionId;
    this.oneSignalId = oneSignalId;
  }

};
