// Generated by CoffeeScript 2.7.0
var ParentPermissionCodes;

import moment from "moment";

export default ParentPermissionCodes = class ParentPermissionCodes {
  constructor(_code = "", _expiration = moment().add(5, "minutes"), _parentPhone = "", _childPhone = '') {
    this.childPhone = _childPhone;
    this.code = _code;
    this.expiration = moment().add(5, "minutes");
    this.parentPhone = _parentPhone;
  }

};

//# sourceMappingURL=parentPermissionCode.js.map
