// Generated by CoffeeScript 2.7.0
var Parent;

import Manager from "../managers/manager";

export default Parent = class Parent {
  constructor(id = Manager.GetUid(), userKey = '', name = '', email = '', phone = '', address = '', parentType = '') {
    this.id = id;
    this.userKey = userKey;
    this.name = name;
    this.email = email;
    this.phone = phone;
    this.address = address;
    this.parentType = parentType;
  }

};

//# sourceMappingURL=parent.js.map
