// Generated by CoffeeScript 2.7.0
var ParentPermissionCodes

import moment from 'moment'

export default ParentPermissionCodes = class ParentPermissionCodes {
  constructor(code = '', expiration = moment().add(5, 'minutes'), parentPhone = '', id = '', childPhone = '') {
    this.code = code
    this.expiration = expiration
    this.parentPhone = parentPhone
    this.id = id
    this.childPhone = childPhone
  }
}

//# sourceMappingURL=parentPermissionCode.js.map
