// Generated by CoffeeScript 2.7.0
var Shortcut;

export default Shortcut = class Shortcut {
  constructor(accessType = '', iconName = '', screenName = '') {
    this.accessType = accessType;
    this.iconName = iconName;
    this.screenName = screenName;
  }

};

//# sourceMappingURL=shortcut.js.map
