// Generated by CoffeeScript 2.7.0
var SwapRequest

import Manager from '../managers/manager'

import DateFormats from '../constants/dateFormats'

import moment from 'moment'

export default SwapRequest = class SwapRequest {
  constructor(
    id = Manager.getUid(),
    startDate = '',
    shareWith = [],
    endDate = '',
    dateAdded = moment().format(DateFormats.dateForDb),
    recipientPhone = '',
    reason = '',
    duration = '',
    ownerPhone = '',
    children = '',
    fromHour = '',
    toHour = '',
    status = 'pending',
    range = [],
    responseDueDate = ''
  ) {
    this.id = id
    this.startDate = startDate
    this.shareWith = shareWith
    this.endDate = endDate
    this.dateAdded = dateAdded
    this.recipientPhone = recipientPhone
    this.reason = reason
    this.duration = duration
    this.ownerPhone = ownerPhone
    this.children = children
    this.fromHour = fromHour
    this.toHour = toHour
    this.status = status
    this.range = range
    this.responseDueDate = responseDueDate
  }
}

//# sourceMappingURL=swapRequest.js.map
