// Generated by CoffeeScript 2.7.0
var SwapRequest;

import Manager from "../managers/manager";

import DateFormats from "../constants/datetimeFormats";

import moment from "moment";

export default SwapRequest = class SwapRequest {
  constructor(id = Manager.GetUid(), startDate = '', shareWith = [], endDate = '', creationDate = moment().format(DateFormats.dateForDb), recipientKey = '', requestReason = '', duration = '', ownerKey = '', recipientName = '', ownerName = '', children = '', fromHour = '', toHour = '', status = 'pending', declineReason = '', responseDate = '', range = [], requestedResponseDate = '') {
    this.id = id;
    this.startDate = startDate;
    this.shareWith = shareWith;
    this.endDate = endDate;
    this.creationDate = creationDate;
    this.recipientKey = recipientKey;
    this.requestReason = requestReason;
    this.duration = duration;
    this.ownerKey = ownerKey;
    this.recipientName = recipientName;
    this.ownerName = ownerName;
    this.children = children;
    this.fromHour = fromHour;
    this.toHour = toHour;
    this.status = status;
    this.declineReason = declineReason;
    this.responseDate = responseDate;
    this.range = range;
    this.requestedResponseDate = requestedResponseDate;
  }

};

//# sourceMappingURL=swapRequest.js.map
