// Generated by CoffeeScript 2.7.0
var TitleSuggestion

export default TitleSuggestion = class TitleSuggestion {
  constructor(ownerPhone = '', formName = '', suggestion = '') {
    this.ownerPhone = ownerPhone
    this.formName = formName
    this.suggestion = suggestion
  }
}
