// Generated by CoffeeScript 2.7.0
var TransferChangeRequest;

import Manager from "../managers/manager";

export default TransferChangeRequest = class TransferChangeRequest {
  constructor(id = Manager.getUid(), startDate = '', endDate = '', time = '', ownerPhone = '', location = '', directionsLink = '', shareWith = [], reason = '', recipientPhone = '', responseDueDate = '', preferredTransferLocation = '') {
    this.id = id;
    this.startDate = startDate;
    this.endDate = endDate;
    this.time = time;
    this.ownerPhone = ownerPhone;
    this.location = location;
    this.directionsLink = directionsLink;
    this.shareWith = shareWith;
    this.reason = reason;
    this.recipientPhone = recipientPhone;
    this.responseDueDate = responseDueDate;
    this.preferredTransferLocation = preferredTransferLocation;
  }

};
