// Generated by CoffeeScript 2.7.0
var TransferChangeRequest

export default TransferChangeRequest = class TransferChangeRequest {
  constructor(
    id = '',
    date = '',
    time = '',
    phone = '',
    location = '',
    createdBy = '',
    directionsLink = '',
    shareWith = [],
    reason = '',
    recipientPhone = '',
    preferredTransferLocation = ''
  ) {
    this.id = id
    this.date = date
    this.time = time
    this.phone = phone
    this.location = location
    this.createdBy = createdBy
    this.directionsLink = directionsLink
    this.shareWith = shareWith
    this.reason = reason
    this.recipientPhone = recipientPhone
    this.preferredTransferLocation = preferredTransferLocation
  }
}

//# sourceMappingURL=transferChangeRequest.js.map
