// Generated by CoffeeScript 2.7.0
var UpdateSubscriber;

UpdateSubscriber = class UpdateSubscriber {
  constructor(id = '', key = '', email = '', subscriptionId = '') {
    this.id = id;
    this.key = key;
    this.email = email;
    this.subscriptionId = subscriptionId;
  }

};

export default UpdateSubscriber;

//# sourceMappingURL=updateSubscriber.js.map
