// Generated by CoffeeScript 2.7.0
var Update;

import DateFormats from "../constants/datetimeFormats";

import moment from "moment";

Update = null;

export default Update = class Update {
  constructor(id = '', creationDate = moment().format(DateFormats.fullDatetime), category = '', recipientKey = '', ownerKey = '', title = '', text = '') {
    this.id = id;
    this.creationDate = creationDate;
    this.category = category;
    this.recipientKey = recipientKey;
    this.ownerKey = ownerKey;
    this.title = title;
    this.text = text;
  }

};

//# sourceMappingURL=update.js.map
