// Generated by CoffeeScript 2.7.0
var UpdateSubscriber

import Manager from '../managers/manager'

UpdateSubscriber = class UpdateSubscriber {
    constructor(options) {
        var ref, ref1, ref2, ref3, ref4
        this.id = Manager.GetUid()
        this.name = (ref = options != null ? options.name : void 0) != null ? ref : ''
        this.phone = (ref1 = options != null ? options.phone : void 0) != null ? ref1 : ''
        this.key = (ref2 = options != null ? options.key : void 0) != null ? ref2 : ''
        this.email = (ref3 = options != null ? options.email : void 0) != null ? ref3 : ''
        this.subscriptionId = (ref4 = options != null ? options.subscriptionId : void 0) != null ? ref4 : ''
    }
}

export default UpdateSubscriber

//# sourceMappingURL=updateSubscriber.js.map