// Generated by CoffeeScript 2.7.0
var User;

import Manager from "../managers/manager";

export default User = class User {
  constructor(_name = 'name', _id = '', _allowNotifications = 'Yes', _email = '', _coparents = [], _children = [], _phone = '', _parentType = '', _accountType = 'parent', _settings = {
      morningReminderSummaryHour: '10am',
      eveningReminderSummaryHour: '8pm'
    }, _updatedApp = false) {
    this.updatedApp = _updatedApp;
    this.name = _name;
    this.email = _email;
    this.phone = _phone;
    this.children = _children;
    this.coparents = _coparents;
    this.parentType = _parentType;
    this.accountType = _accountType;
    this.allowNotifications = _allowNotifications;
    this.parentType = _parentType;
    this.id = Manager.getUid();
    this.settings = _settings;
  }

};

//# sourceMappingURL=user.js.map
