// Generated by CoffeeScript 2.7.0
var UserKey;

import Manager from "../managers/manager";

export default UserKey = class UserKey {
  constructor(id = Manager.getUid(), key = '', email = '') {
    this.id = id;
    this.key = key;
    this.email = email;
  }

};
