// Generated by CoffeeScript 2.7.0
var User;

import Manager from "../managers/manager";

export default User = class User {
  constructor(name = '', email = '', phone = '', children = [], coparents = [], parentType = '', accountType = '', allowNotifications = '', id = Manager.getUid(), emailVerified = false, defaultTransferLocation = '', defaultTransferNavLink = '', settings = {
      morningReminderSummaryHour: '10am',
      eveningReminderSummaryHour: '8pm'
    }) {
    this.name = name;
    this.email = email;
    this.phone = phone;
    this.children = children;
    this.coparents = coparents;
    this.parentType = parentType;
    this.accountType = accountType;
    this.allowNotifications = allowNotifications;
    this.id = id;
    this.emailVerified = emailVerified;
    this.defaultTransferLocation = defaultTransferLocation;
    this.defaultTransferNavLink = defaultTransferNavLink;
    this.settings = settings;
  }

};

//# sourceMappingURL=user.js.map
