// Generated by CoffeeScript 2.7.0
var User;

import Manager from "../managers/manager";

export default User = class User {
  constructor(id = Manager.getUid(), name = '', email = '', phone = '', children = [], childAccounts = [], coparents = [], parentType = '', accountType = '', notificationsEnabled = '', settings = {
      theme: 'light'
    }, dailySummaries = {
      morningSentDate: '',
      eveningSentDate: '',
      morningReminderSummaryHour: '10am',
      eveningReminderSummaryHour: '8pm'
    }, visitation = {
      transferLocation: '',
      transferLocationNavLink: '',
      visitationSchedule: '',
      visitationHolidays: []
    }) {
    this.id = id;
    this.name = name;
    this.email = email;
    this.phone = phone;
    this.children = children;
    this.childAccounts = childAccounts;
    this.coparents = coparents;
    this.parentType = parentType;
    this.accountType = accountType;
    this.notificationsEnabled = notificationsEnabled;
    this.settings = settings;
    this.dailySummaries = dailySummaries;
    this.visitation = visitation;
  }

};
