// Generated by CoffeeScript 2.7.0
import Swal from "sweetalert2";

// Strings
export var toCamelCase = function(str) {
  return str.replace(/(?:^\w|[A-Z]|\b\w)/g, function(word, index) {
    if (index === 0) {
      return word.toLowerCase();
    } else {
      return word.toUpperCase();
    }
  });
  str = str.replace(/\s+/g, '').replaceAll(" ", "");
  return str;
};

export var capitalizeFirstWord = function(str) {
  var capitalizedFirstWord, firstWord;
  firstWord = str.split(' ')[0];
  capitalizedFirstWord = firstWord.charAt(0).toUpperCase() + firstWord.slice(1);
  return capitalizedFirstWord + str.slice(firstWord.length);
};

export var hasClass = function(element, className) {
  if (element.classList.contains(className)) {
    return true;
  } else {
    return false;
  }
};

export var formatTitleWords = function(str) {
  return str = str.replaceAll("To", "to").replaceAll("Vs", "vs").replaceAll("With", "with").replaceAll("At", "at").replaceAll("From", "from").replaceAll("The", "the").replaceAll("And", "and");
};

export var getFirstWord = function(input) {
  return input.toString().replace(/ .*/, '');
};

export var formatFileName = function(input) {
  return input.replace('.docx', '').replace('.doc', '').replace('.pdf', '');
};

export var getFileExtension = function(fileName) {
  return fileName.split('.').pop();
};

export var isAllUppercase = function(input) {
  return input === input.toUpperCase();
};

export var formatTocHeader = function(header) {
  return header.replace(/[0-9]/g, '').replace('.', '').replace(/\s+/g, '');
};

export var removeSpacesAndLowerCase = function(input) {
  return input.replace(/\s+/g, '').toLowerCase();
};

export var stringHasNumbers = function(input) {
  return /\d/.test(input);
};

export var contains = function(itemToCheck, searchValue) {
  if (!itemToCheck) {
    return false;
  }
  return itemToCheck.indexOf(searchValue) > -1;
};

export var wordCount = function(input) {
  return input.trim().split(/\s+/).length;
};

export var getPositionOfWordInText = function(word, text) {
  var endIndex, index, indexAfterStartOfText, returnObj, startOfTextToWord, textLength;
  index = text.indexOf(word);
  textLength = text.length;
  startOfTextToWord = text.substring(0, index);
  indexAfterStartOfText = startOfTextToWord.length;
  endIndex = indexAfterStartOfText + textLength;
  returnObj = {
    start: indexAfterStartOfText,
    end: endIndex
  };
  return returnObj;
};

export var uppercaseFirstLetterOfAllWords = function(input) {
  var words;
  words = input.toString();
  if (words && words !== void 0) {
    if (words.indexOf('-') > -1) {
      words = input.replace(/-/g, ' ').split(' ');
    } else {
      words = words.split(' ');
    }
    words = words.filter(function(x) {
      return x.length > 0;
    });
    words = words.map(function(word) {
      return word[0].toUpperCase() + word.substr(1);
    });
    if (words.length > 0) {
      words = words.join(' ');
    }
  }
  return words;
};

export var spaceBetweenWords = function(input) {
  return input.toString().replace(/([a-z])([A-Z])/g, '$1 $2');
};

export var formatNameFirstNameOnly = function(input) {
  var returnString;
  if (!input) {
    return input;
  }
  returnString = input.toString();
  if (!returnString || returnString.length === 0) {
    return returnString;
  }
  returnString = returnString.split(' ')[0];
  return uppercaseFirstLetterOfAllWords(returnString);
};

export var camelCaseToString = function(word) {
  var result;
  result = word.replace(/([A-Z])/g, ' $1');
  return result.charAt(0).toUpperCase() + result.slice(1);
};

export var formatPhone = function(input) {
  input = input.toString().replace(/-/g, '').replace(/\s+/g, '').replace(/\(/g, '').replace(/\)/g, '').replace(/\+/g, '').replace(/\+1/g, '');
  return input;
};

export var formatDbProp = function(prop) {
  prop = toCamelCase(prop).replaceAll(" ", "");
  return prop;
};

export var lowercaseShouldBeLowercase = function(input) {
  return input.replace("Of", "of");
};

export var removeFileExtension = function(input) {
  return input.replace(/\.[^\/.]+$/, '');
};

// Arrays
export var uniqueArray = function(array) {
  return Array.from(new Set(array));
};

export var displayAlert = function(type, title, text = '', onConfirm) {
  switch (true) {
    case type === "input":
      return Swal.fire({
        title: title,
        text: text,
        icon: '',
        input: 'text',
        showCancelButton: true,
        confirmButtonText: "Confirm",
        showClass: {
          popup: `animate__animated
animate__fadeInUp
animate__faster`
        },
        hideClass: {
          popup: `animate__animated
animate__fadeOutDown
animate__faster`
        }
      }).then(function(result) {
        if (result.isConfirmed) {
          if (onConfirm) {
            return onConfirm(result);
          }
        }
      });
    case type === "error":
      return Swal.fire({
        title: title,
        text: text,
        icon: 'error',
        showClass: {
          popup: `animate__animated
animate__fadeInUp
animate__faster`
        },
        hideClass: {
          popup: `animate__animated
animate__fadeOutDown
animate__faster`
        }
      });
  }
};

//# sourceMappingURL=globalFunctions.js.map
