// Generated by CoffeeScript 2.7.0
// Strings
export var toCamelCase = function(input) {
  return input.toString().replace(/(?:^\w|[A-Z]|\b\w)/g, function(word, index) {
    if (index === 0) {
      word.toLowerCase();
    } else {
      word.toUpperCase();
    }
    return input.replace(/\s+/g, '');
  });
};

export var getFirstWord = function(input) {
  return input.toString().replace(/ .*/, '');
};

export var formatFileName = function(input) {
  return input.replace('.docx', '').replace('.doc', '').replace('.pdf', '');
};

export var getFileExtension = function(fileName) {
  return fileName.split('.').pop();
};

export var isAllUppercase = function(input) {
  return input === input.toUpperCase();
};

export var formatTocHeader = function(header) {
  return header.replace(/[0-9]/g, '').replace('.', '').replace(/\s+/g, '');
};

export var removeSpacesAndLowerCase = function(input) {
  return input.replace(/\s+/g, '').toLowerCase();
};

export var stringHasNumbers = function(input) {
  return /\d/.test(input);
};

export var contains = function(itemToCheck, searchValue) {
  return itemToCheck.indexOf(searchValue) > -1;
};

export var wordCount = function(input) {
  return input.trim().split(/\s+/).length;
};

export var uppercaseFirstLetterOfAllWords = function(input) {
  var words;
  words = input.toString();
  if (words && words !== void 0) {
    if (words.indexOf('-') > -1) {
      words = input.replace(/-/g, ' ').split(' ');
    } else {
      words = words.split(' ');
    }
    words = words.filter(function(x) {
      return x.length > 0;
    });
    words = words.map(function(word) {
      return word[0].toUpperCase() + word.substr(1);
    });
    if (words.length > 0) {
      words = words.join(' ');
    }
  }
  return words;
};

export var spaceBetweenWords = function(input) {
  return input.toString().replace(/([a-z])([A-Z])/g, '$1 $2');
};

export var formatNameFirstNameOnly = function(input) {
  var returnString;
  returnString = input.toString();
  if (!returnString || returnString.length === 0) {
    return returnString;
  }
  returnString = returnString.split(' ')[0];
  return uppercaseFirstLetterOfAllWords(returnString);
};

export var camelCaseToString = function(word) {
  var result;
  result = word.replace(/([A-Z])/g, ' $1');
  return result.charAt(0).toUpperCase() + result.slice(1);
};

export var formatPhone = function(input) {
  return input.toString().replace(/-/g, '').replace(/\s+/g, '').replace(/\(/g, '').replace(/\)/g, '').replace(/\+/g, '').replace(/\+1/g, '');
};

export var removeFileExtension = function(input) {
  return input.replace(/\.[^\/.]+$/, '');
};

// Arrays
export var uniqueArray = function(array) {
  return Array.from(new Set(array));
};

//# sourceMappingURL=globalFunctions.js.map
